# Importation

In [250]:
import pandas as pd
import numpy as np

In [251]:
#After Concatenisation
df_offensive = pd.read_csv('Offensive_Whoscored_Data.csv')
df_passing = pd.read_csv('Passing_Whoscored_Data.csv')
df_summary = pd.read_csv('Summary_Whoscored_Data.csv')
df_defensive = pd.read_csv('Defensive_Whoscored_Data.csv')

C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\2725428501.py:2: DtypeWarning: Columns (6,7,8,9,10,11,12,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df_offensive = pd.read_csv('Offensive_Whoscored_Data.csv')
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\2725428501.py:3: DtypeWarning: Columns (6,7,8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_passing = pd.read_csv('Passing_Whoscored_Data.csv')
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\2725428501.py:4: DtypeWarning: Columns (6,7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_summary = pd.read_csv('Summary_Whoscored_Data.csv')
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\2725428501.py:5: DtypeWarning: Columns (6,7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_defensive = pd.read_csv('Defensive_Whoscored_Data.csv')

In [252]:
#Position
df_defense = pd.read_csv('defensive_players.csv')
df_forward = pd.read_csv('forward_players.csv')
df_goal = pd.read_csv('goalkeeper_players.csv')
df_midfield = pd.read_csv('midfield_players.csv')

In [253]:
#Merge all
df_merged = pd.read_csv('Merged_players_Whoscored.csv')
df_merged.Saison

0        2018
1        2018
2        2018
3        2018
4        2018
         ...
20502    2020
20503    2020
20504    2020
20505    2020
20506    2011
Name: Saison, Length: 20507, dtype: int64

In [254]:
#Selecting only the needed columns for the forecasting process

merged_rating_players = df_merged[['Name', 'Saison', 'Rating', 'Age']]
merged_rating_players = merged_rating_players[merged_rating_players['Saison'].notnull()].copy()
merged_rating_players

                    Name  Saison  Rating  Age
0           Bobby Allain    2018    7.13   27
1         Walter Benítez    2018    7.05   26
2       Gianluigi Buffon    2018    6.88   40
3       Benjamin Lecomte    2018    6.86   28
4       Stéphane Ruffier    2018    6.86   32
...                  ...     ...     ...  ...
20502        Salih Özcan    2020    6.28   22
20503     Julian Ryerson    2020    6.28   23
20504    Bastian Oczipka    2020    6.24   31
20505  Alessandro Schöpf    2020    6.05   26
20506  Grégory Bourillon    2011    7.02   27

[20507 rows x 4 columns]

In [255]:
merged_rating_players.loc[merged_rating_players.Name == 'Kylian Mbappé']

                Name  Saison  Rating  Age
2565   Kylian Mbappé    2021    8.04   23
3676   Kylian Mbappé    2020    7.68   22
8997   Kylian Mbappé    2017    7.54   19
10896  Kylian Mbappé    2016    7.22   18
13847  Kylian Mbappé    2018    8.00   20
15015  Kylian Mbappé    2022    7.79   24
18441  Kylian Mbappé    2019    8.14   21

In [256]:
#Store a list of all the players
nameList = merged_rating_players.Name.unique()

#create a dataframe just to store the mean values of player rating's 
df_mean = pd.DataFrame(columns=['Name', 'Mean', 'Growth'])
df_mean

Empty DataFrame
Columns: [Name, Mean, Growth]
Index: []

In [257]:
#Calculating career growth and rating avergae of every player (Feature engineering)
for name in nameList:
    mean = merged_rating_players.loc[merged_rating_players.Name == name]['Rating'].mean()
    length = len(merged_rating_players.loc[merged_rating_players.Name == name]['Rating'])
    growth = merged_rating_players.loc[merged_rating_players.Name == name]['Rating'].tolist()[length-1] - merged_rating_players.loc[merged_rating_players.Name == name]['Rating'].tolist()[0]
    df_mean.at[name, 'Name'] = name
    df_mean.at[name, 'Mean'] = mean
    df_mean.at[name, 'Growth'] = growth
    
#Merging all the data together   
merged_rating_players = pd.merge(merged_rating_players, df_mean, on=['Name'])

#Converting column type
merged_rating_players['Mean'] = merged_rating_players['Mean'].astype(np.float64)
merged_rating_players

                   Name  Saison  Rating  Age   Mean Growth
0          Bobby Allain    2018    7.13   27  7.130    0.0
1        Walter Benítez    2018    7.05   26  6.814  -0.26
2        Walter Benítez    2020    6.69   28  6.814  -0.26
3        Walter Benítez    2019    6.94   27  6.814  -0.26
4        Walter Benítez    2017    6.60   25  6.814  -0.26
...                 ...     ...     ...  ...    ...    ...
20502    Sebastián Leto    2013    6.39   27  6.390    0.0
20503    Matías Cabrera    2013    6.35   28  6.350    0.0
20504       Timo Becker    2020    6.36   23  6.360    0.0
20505  Jean-Manuel Mbom    2020    6.34   20  6.340    0.0
20506       Hannes Wolf    2020    6.32   21  6.320    0.0

[20507 rows x 6 columns]

In [258]:
merged_rating_players.loc[merged_rating_players.Name == 'Lionel Messi']

              Name  Saison  Rating  Age    Mean Growth
5747  Lionel Messi    2021    7.77   34  8.5575   1.07
5748  Lionel Messi    2009    8.67   22  8.5575   1.07
5749  Lionel Messi    2018    8.48   31  8.5575   1.07
5750  Lionel Messi    2011    8.88   24  8.5575   1.07
5751  Lionel Messi    2015    8.46   28  8.5575   1.07
5752  Lionel Messi    2012    8.83   25  8.5575   1.07
5753  Lionel Messi    2016    8.47   29  8.5575   1.07
5754  Lionel Messi    2017    8.68   30  8.5575   1.07
5755  Lionel Messi    2010    8.76   23  8.5575   1.07
5756  Lionel Messi    2022    8.51   35  8.5575   1.07
5757  Lionel Messi    2013    8.34   26  8.5575   1.07
5758  Lionel Messi    2014    8.84   27  8.5575   1.07

In [259]:
merged_rating_players.loc[merged_rating_players.Name == 'Kylian Mbappé']

               Name  Saison  Rating  Age      Mean Growth
5740  Kylian Mbappé    2021    8.04   23  7.772857    0.1
5741  Kylian Mbappé    2020    7.68   22  7.772857    0.1
5742  Kylian Mbappé    2017    7.54   19  7.772857    0.1
5743  Kylian Mbappé    2016    7.22   18  7.772857    0.1
5744  Kylian Mbappé    2018    8.00   20  7.772857    0.1
5745  Kylian Mbappé    2022    7.79   24  7.772857    0.1
5746  Kylian Mbappé    2019    8.14   21  7.772857    0.1

In [260]:
#Another portion of feature engineering

from pandas import Series
from pandas import DataFrame
from pandas import concat

merged_rating_players = merged_rating_players.sort_values(['Saison', 'Name'])
merged_rating_players_tree = merged_rating_players.sort_values(['Saison', 'Name'])

#Creating 2 new features for every player by combining both the last season rating and the difference between that and the
#~previous season rating

df_transformedPlayer = merged_rating_players.copy()
df_transformedPlayer['Last_Season_Rating'] = df_transformedPlayer.groupby(['Name'])['Rating'].shift()
df_transformedPlayer['Last_Season_Diff'] = df_transformedPlayer.groupby('Name')['Last_Season_Rating'].transform(Series.diff)
df_transformedPlayer = df_transformedPlayer.dropna()
df_transformedPlayer.head()

,Name,Saison,Rating,Age,Mean,Growth,Last_Season_Rating,Last_Season_Diff
12978,Abdoulrazak Boukari,2010,6.84,24,6.840000,0.09,6.93,0.18
16362,Alessandro Matri,2010,6.79,26,6.713750,-0.47,6.92,-0.06
2298,Anderson,2010,6.16,23,6.806667,-0.79,6.95,0.11
15883,Andrea Barzagli,2010,6.86,29,6.971111,-0.28,7.27,0.57
15759,Andrea Ranocchia,2010,7.16,22,7.157778,-0.23,7.48,0.17

In [261]:
df_transformedPlayer_tree = merged_rating_players_tree.copy()
df_transformedPlayer_tree['Last_Season_Rating'] = df_transformedPlayer_tree.groupby(['Name'])['Rating'].shift()
df_transformedPlayer_tree['Last_Season_Diff'] = df_transformedPlayer_tree.groupby('Name')['Last_Season_Rating'].transform(Series.diff)
df_transformedPlayer_tree = df_transformedPlayer_tree.dropna()
df_transformedPlayer_tree.head()

,Name,Saison,Rating,Age,Mean,Growth,Last_Season_Rating,Last_Season_Diff
12978,Abdoulrazak Boukari,2010,6.84,24,6.840000,0.09,6.93,0.18
16362,Alessandro Matri,2010,6.79,26,6.713750,-0.47,6.92,-0.06
2298,Anderson,2010,6.16,23,6.806667,-0.79,6.95,0.11
15883,Andrea Barzagli,2010,6.86,29,6.971111,-0.28,7.27,0.57
15759,Andrea Ranocchia,2010,7.16,22,7.157778,-0.23,7.48,0.17

In [262]:
df_transformedPlayer

,Name,Saison,Rating,Age,Mean,Growth,Last_Season_Rating,Last_Season_Diff
12978,Abdoulrazak Boukari,2010,6.84,24,6.840000,0.09,6.93,0.18
16362,Alessandro Matri,2010,6.79,26,6.713750,-0.47,6.92,-0.06
2298,Anderson,2010,6.16,23,6.806667,-0.79,6.95,0.11
15883,Andrea Barzagli,2010,6.86,29,6.971111,-0.28,7.27,0.57
15759,Andrea Ranocchia,2010,7.16,22,7.157778,-0.23,7.48,0.17
...,...,...,...,...,...,...,...,...
11885,Youri Tielemans,2022,6.86,25,6.952857,-0.19,6.90,-0.19
6241,Youssouf Fofana,2022,6.93,24,6.757500,0.21,6.72,-0.09
6175,Yunis Abdelhamid,2022,6.97,35,6.925000,0.34,6.76,-0.13
6226,Zeki Çelik,2022,6.66,26,6.780000,0.0,6.73,-0.27
5840,Ángel Di María,2022,6.98,35,7.354615,0.58,7.17,-0.16

In [263]:
df_transformedPlayer_tree

,Name,Saison,Rating,Age,Mean,Growth,Last_Season_Rating,Last_Season_Diff
12978,Abdoulrazak Boukari,2010,6.84,24,6.840000,0.09,6.93,0.18
16362,Alessandro Matri,2010,6.79,26,6.713750,-0.47,6.92,-0.06
2298,Anderson,2010,6.16,23,6.806667,-0.79,6.95,0.11
15883,Andrea Barzagli,2010,6.86,29,6.971111,-0.28,7.27,0.57
15759,Andrea Ranocchia,2010,7.16,22,7.157778,-0.23,7.48,0.17
...,...,...,...,...,...,...,...,...
11885,Youri Tielemans,2022,6.86,25,6.952857,-0.19,6.90,-0.19
6241,Youssouf Fofana,2022,6.93,24,6.757500,0.21,6.72,-0.09
6175,Yunis Abdelhamid,2022,6.97,35,6.925000,0.34,6.76,-0.13
6226,Zeki Çelik,2022,6.66,26,6.780000,0.0,6.73,-0.27
5840,Ángel Di María,2022,6.98,35,7.354615,0.58,7.17,-0.16

# Linear Regression

In [264]:
#Forecasting using linear regression

from statistics import mean 
from sklearn import linear_model 

from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import median_absolute_error
from sklearn import model_selection
from math import sqrt

accuracy_MSE = []
accuracy_RMSE = []
accuracy_MAE = []
accuracy_R2 = []

#For every season using previous season data to forecast current season rating
for season in range(2011,2022):
    
    training_set = df_transformedPlayer[df_transformedPlayer['Saison'] == season-1]
    testing_set = df_transformedPlayer[df_transformedPlayer['Saison'] == season]

    X_train = training_set.drop(['Rating', 'Name', 'Saison'], axis=1)
    y_train = training_set['Rating'].values
    X_test = testing_set.drop(['Rating', 'Name', 'Saison'], axis=1)
    y_test = testing_set['Rating'].values

    lin_reg = linear_model.LinearRegression(n_jobs=-1) 
    
    lin_reg.fit(X_train, y_train)

    #using k-folds cross validation for calculating forecast accuracy
    scores = cross_val_score(lin_reg, X_test, y_test, cv=10)
    accuracy_R2.append(scores.mean())
    
    y_pred = lin_reg.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    rmse = sqrt(mse)
    mae = median_absolute_error(y_test, y_pred)
    
    accuracy_MSE.append(mse)
    accuracy_RMSE.append(rmse)
    accuracy_MAE.append(mae)
     
print('Average accuracy for forecasting player ratings between 2010-2022:')
print("MSE: " + "{:.2f}".format(mean(accuracy_MSE)))
print("RMSE: " + "{:.2f}".format(mean(accuracy_RMSE)))
print("MAE: " + "{:.2f}".format(mean(accuracy_MAE)))
print("R2: " + "{:.2f}".format(mean(accuracy_R2)))

Average accuracy for forecasting player ratings between 2010-2022:
MSE: 0.04
RMSE: 0.19
MAE: 0.12
R2: 0.59

In [265]:
df_transformedPlayer

,Name,Saison,Rating,Age,Mean,Growth,Last_Season_Rating,Last_Season_Diff
12978,Abdoulrazak Boukari,2010,6.84,24,6.840000,0.09,6.93,0.18
16362,Alessandro Matri,2010,6.79,26,6.713750,-0.47,6.92,-0.06
2298,Anderson,2010,6.16,23,6.806667,-0.79,6.95,0.11
15883,Andrea Barzagli,2010,6.86,29,6.971111,-0.28,7.27,0.57
15759,Andrea Ranocchia,2010,7.16,22,7.157778,-0.23,7.48,0.17
...,...,...,...,...,...,...,...,...
11885,Youri Tielemans,2022,6.86,25,6.952857,-0.19,6.90,-0.19
6241,Youssouf Fofana,2022,6.93,24,6.757500,0.21,6.72,-0.09
6175,Yunis Abdelhamid,2022,6.97,35,6.925000,0.34,6.76,-0.13
6226,Zeki Çelik,2022,6.66,26,6.780000,0.0,6.73,-0.27
5840,Ángel Di María,2022,6.98,35,7.354615,0.58,7.17,-0.16

In [266]:
#Forecasting player ratings between 2019-2025

for season in range(2019, 2025):
    
    previousPlayers = merged_rating_players.loc[merged_rating_players.Saison == season].copy()
    currentPlayers = merged_rating_players.loc[merged_rating_players.Saison == season+1].copy()
    futurePlayers = currentPlayers.copy()

    futurePlayers['Saison'] = currentPlayers['Saison'].values+1
    futurePlayers['Age'] = currentPlayers['Age'].values+1

    futurePlayers.drop(['Rating'], axis=1)

    li = []
    li.append(previousPlayers)
    li.append(currentPlayers)
    li.append(futurePlayers)

    df_combined = pd.concat(li)
    
    df_combined = df_combined.sort_values(['Saison', 'Name'])

    df_transformedPlayer = df_combined.copy()
    df_transformedPlayer['Last_Season_Rating'] = df_transformedPlayer.groupby(['Name'])['Rating'].shift()
    df_transformedPlayer['Last_Season_Diff'] = df_transformedPlayer.groupby('Name')['Last_Season_Rating'].transform(Series.diff)
    df_transformedPlayer = df_transformedPlayer.dropna()
    
    df_transformedPlayer = df_transformedPlayer.loc[df_transformedPlayer['Saison'] == season+2]
    
    currentSeasonDf = df_transformedPlayer.drop(['Rating', 'Name', 'Saison'], axis=1)
    y_pred = lin_reg.predict(currentSeasonDf)

    #Attaching the predicted values to the original DF so that the cycle can continue 
    #~until the forecasting range comes to an end 
    ratings = ["{:.2f}".format(value) for value in y_pred.tolist()]
    df_transformedPlayer['Rating'] = ratings
    df_transformedPlayer['Rating'] = y_pred.round(2)
    df_transformedPlayer = df_transformedPlayer[['Name', 'Saison', 'Rating', 'Age', 'Mean', 'Growth']]
    merged_rating_players = merged_rating_players.append(df_transformedPlayer, ignore_index=True)
    merged_rating_players.drop_duplicates(subset=['Name', 'Saison'], keep='last', inplace=True)  # ajout de cette ligne
    merged_rating_players = merged_rating_players[merged_rating_players['Rating'].notnull()].copy()
    merged_rating_players['Rating'] = merged_rating_players['Rating'].astype(float)

C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\47488211.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players = merged_rating_players.append(df_transformedPlayer, ignore_index=True)
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\47488211.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players = merged_rating_players.append(df_transformedPlayer, ignore_index=True)
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\47488211.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players = merged_rating_players.append(df_transformedPlayer, ignore_index=True)
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\47488211.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players = merged_rating_players.append(df_transformedPlayer, ignore_index=True)
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\47488211.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players = merged_rating_players.append(df_transformedPlayer, ignore_index=True)
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\47488211.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players = merged_rating_players.append(df_transformedPlayer, ignore_index=True)

In [267]:
merged_rating_players.loc[merged_rating_players.Name == 'Kylian Mbappé']

                Name  Saison  Rating  Age      Mean Growth
12074  Kylian Mbappé    2016    7.22   18  7.772857    0.1
13696  Kylian Mbappé    2017    7.54   19  7.772857    0.1
15304  Kylian Mbappé    2018    8.00   20  7.772857    0.1
16634  Kylian Mbappé    2019    8.14   21  7.772857    0.1
17716  Kylian Mbappé    2020    7.68   22  7.772857    0.1
19589  Kylian Mbappé    2021    7.72   23  7.772857    0.1
20299  Kylian Mbappé    2022    7.74   24  7.772857    0.1
21153  Kylian Mbappé    2023    7.72   25  7.772857    0.1
22067  Kylian Mbappé    2024    7.69   26  7.772857    0.1
22981  Kylian Mbappé    2025    7.66   27  7.772857    0.1
23895  Kylian Mbappé    2026    7.64   28  7.772857    0.1

In [268]:
merged_rating_players.loc[merged_rating_players.Name == 'Lionel Messi']

               Name  Saison  Rating  Age    Mean Growth
896    Lionel Messi    2009    8.67   22  8.5575   1.07
2469   Lionel Messi    2010    8.76   23  8.5575   1.07
4070   Lionel Messi    2011    8.88   24  8.5575   1.07
5658   Lionel Messi    2012    8.83   25  8.5575   1.07
7240   Lionel Messi    2013    8.34   26  8.5575   1.07
8888   Lionel Messi    2014    8.84   27  8.5575   1.07
10528  Lionel Messi    2015    8.46   28  8.5575   1.07
12110  Lionel Messi    2016    8.47   29  8.5575   1.07
13726  Lionel Messi    2017    8.68   30  8.5575   1.07
15334  Lionel Messi    2018    8.48   31  8.5575   1.07
18535  Lionel Messi    2021    7.77   34  8.5575   1.07
19017  Lionel Messi    2022    8.51   35  8.5575   1.07
21172  Lionel Messi    2023    8.20   36  8.5575   1.07
22086  Lionel Messi    2024    8.08   37  8.5575   1.07
23000  Lionel Messi    2025    8.07   38  8.5575   1.07
23914  Lionel Messi    2026    8.05   39  8.5575   1.07

In [269]:
#write the DF to a csv file
merged_rating_players.to_csv('Forecasted_Ratings_2022-2025_linear.csv', index = False)

# Decision Tree Regression

In [270]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
import numpy as np

# Préparation des données d'entraînement et de test
X = df_transformedPlayer_tree.drop(['Rating', 'Name', 'Saison'], axis=1)
y = df_transformedPlayer_tree['Rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Initialisation et entraînement du modèle
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X_train, y_train)

# Prédiction sur les données de test
y_pred = regressor.predict(X_test)

# Évaluation de la performance du modèle
print("MSE:", mean_squared_error(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("R2 score:", r2_score(y_test, y_pred))

MSE: 0.07797282398452612
MAE: 0.21561895551257254
R2 score: 0.18524662551822846

In [271]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
import numpy as np
from statistics import mean 
from math import sqrt

# Définition des modèles à tester
models = [
    DecisionTreeRegressor(random_state=0),
    Ridge(alpha=1.0),
    SVR(kernel='linear', C=1.0),
    SVR(kernel='rbf', C=1.0, gamma='scale'),
    RandomForestRegressor(n_estimators=100, random_state=0),
    KNeighborsRegressor(n_neighbors=5)
]
accuracy_MSE = []
accuracy_RMSE = []
accuracy_MAE = []
accuracy_R2 = []

# Stockage des résultats pour chaque modèle
results = {}

for season in range(2010,2022):
    # Préparation des données d'entraînement et de test
    X = df_transformedPlayer_tree.drop(['Rating', 'Name', 'Saison'], axis=1)
    y = df_transformedPlayer_tree['Rating']
           
    training_set = df_transformedPlayer_tree[df_transformedPlayer_tree['Saison'] == season-1]
    testing_set = df_transformedPlayer_tree[df_transformedPlayer_tree['Saison'] == season]

    X_train = training_set.drop(['Rating', 'Name', 'Saison'], axis=1)
    y_train = training_set['Rating'].values
    X_test = testing_set.drop(['Rating', 'Name', 'Saison'], axis=1)
    y_test = testing_set['Rating'].values

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
    
for model in models:
        # Initialisation et entraînement du modèle
        reg = model.fit(X_train, y_train)

        # Prédiction sur les données de test
        y_pred = model.predict(X_test)

        # Using k-folds cross validation for calculating forecast accuracy
        scores = cross_val_score(model, X_test, y_test, cv=10)
        accuracy_R2.append(scores.mean())

        mse = mean_squared_error(y_test, y_pred)
        rmse = sqrt(mse)
        mae = median_absolute_error(y_test, y_pred)
        r2_scor = r2_score(y_test, y_pred)

        accuracy_MSE.append(mse)
        accuracy_RMSE.append(rmse)
        accuracy_MAE.append(mae)

        model_name = type(model).__name__
        if model_name not in results:
            results[model_name] = {
                "MSE": [],
                "RMSE": [],
                "MAE": [],
                "R2": [],
                "R2_score":[]
            }

        results[model_name]["MSE"].append(mse)
        results[model_name]["RMSE"].append(rmse)
        results[model_name]["MAE"].append(mae)
        results[model_name]["R2_score"].append(r2_scor)

print('Average accuracy for forecasting player ratings between 2010-2022:')
for model_name in results:
    print(model_name)
    print("MSE: " + "{:.2f}".format(mean(results[model_name]["MSE"])))
    print("RMSE: " + "{:.2f}".format(mean(results[model_name]["RMSE"])))
    print("MAE: " + "{:.2f}".format(mean(results[model_name]["MAE"])))
    print("R2: " + "{:.2f}".format(mean(results[model_name]["R2_score"])))

Average accuracy for forecasting player ratings between 2010-2022:
DecisionTreeRegressor
MSE: 0.08
RMSE: 0.28
MAE: 0.18
R2: 0.19
Ridge
MSE: 0.04
RMSE: 0.20
MAE: 0.13
R2: 0.57
SVR
MSE: 0.04
RMSE: 0.20
MAE: 0.13
R2: 0.56
RandomForestRegressor
MSE: 0.04
RMSE: 0.21
MAE: 0.13
R2: 0.55
KNeighborsRegressor
MSE: 0.05
RMSE: 0.23
MAE: 0.15
R2: 0.44

Les trois modèles Ridge, SVR et RandomForestRegressor ont des performances similaires en termes de MSE, RMSE et R2, mais le modèle RandomForestRegressor a la plus petite valeur pour MAE. Cela suggère qu'il a une meilleure performance en termes d'erreur absolue moyenne, ce qui signifie qu'il devrait être en mesure de prédire plus précisément la valeur absolue des résultats. Par conséquent, nous allons utiliser le modèle RandomForestRegressor.

In [272]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
import numpy as np
from statistics import mean 
from math import sqrt

models = []
accuracy_MSE = []
accuracy_RMSE = []
accuracy_MAE = []
accuracy_R2 = []


for season in range(2010,2022):
    # Préparation des données d'entraînement et de test
    X = df_transformedPlayer_tree.drop(['Rating', 'Name', 'Saison'], axis=1)
    y = df_transformedPlayer_tree['Rating']
           
    training_set = df_transformedPlayer_tree[df_transformedPlayer_tree['Saison'] == season-1]
    testing_set = df_transformedPlayer_tree[df_transformedPlayer_tree['Saison'] == season]

    X_train = training_set.drop(['Rating', 'Name', 'Saison'], axis=1)
    y_train = training_set['Rating'].values
    X_test = testing_set.drop(['Rating', 'Name', 'Saison'], axis=1)
    y_test = testing_set['Rating'].values

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

    # Initialisation et entraînement du modèle
    regressor = RandomForestRegressor(random_state=0)
    reg = regressor.fit(X_train, y_train)

    # Prédiction sur les données de test
    y_pred = regressor.predict(X_test)
    models.append(reg)
    
    # Using k-folds cross validation for calculating forecast accuracy
    scores = cross_val_score(regressor, X_test, y_test, cv=10)
    accuracy_R2.append(scores.mean())

    mse = mean_squared_error(y_test, y_pred)
    rmse = sqrt(mse)
    mae = median_absolute_error(y_test, y_pred)

    accuracy_MSE.append(mse)
    accuracy_RMSE.append(rmse)
    accuracy_MAE.append(mae)

print('Average accuracy for forecasting player ratings between 2010-2022:')
print("MSE: " + "{:.2f}".format(mean(accuracy_MSE)))
print("RMSE: " + "{:.2f}".format(mean(accuracy_RMSE)))
print("MAE: " + "{:.2f}".format(mean(accuracy_MAE)))
print("R2: " + "{:.2f}".format(mean(accuracy_R2)))
print("R2 score:", r2_score(y_test, y_pred))

Average accuracy for forecasting player ratings between 2010-2022:
MSE: 0.04
RMSE: 0.21
MAE: 0.13
R2: 0.51
R2 score: 0.5531483890328868

In [273]:
df_transformedPlayer_tree

,Name,Saison,Rating,Age,Mean,Growth,Last_Season_Rating,Last_Season_Diff
12978,Abdoulrazak Boukari,2010,6.84,24,6.840000,0.09,6.93,0.18
16362,Alessandro Matri,2010,6.79,26,6.713750,-0.47,6.92,-0.06
2298,Anderson,2010,6.16,23,6.806667,-0.79,6.95,0.11
15883,Andrea Barzagli,2010,6.86,29,6.971111,-0.28,7.27,0.57
15759,Andrea Ranocchia,2010,7.16,22,7.157778,-0.23,7.48,0.17
...,...,...,...,...,...,...,...,...
11885,Youri Tielemans,2022,6.86,25,6.952857,-0.19,6.90,-0.19
6241,Youssouf Fofana,2022,6.93,24,6.757500,0.21,6.72,-0.09
6175,Yunis Abdelhamid,2022,6.97,35,6.925000,0.34,6.76,-0.13
6226,Zeki Çelik,2022,6.66,26,6.780000,0.0,6.73,-0.27
5840,Ángel Di María,2022,6.98,35,7.354615,0.58,7.17,-0.16

In [274]:
merged_rating_players_tree

                         Name  Saison  Rating  Age      Mean Growth
2042             Aaron Hughes    2009    6.95   30  6.880000  -0.33
3972               Aaron Hunt    2009    7.15   23  7.023750  -0.14
2544             Aaron Lennon    2009    7.33   22  6.710909  -0.56
19616           Aaron Mokoena    2009    6.56   29  6.560000    0.0
10711  Abdelhamid El Kaoutari    2009    6.70   20  6.866667  -0.58
...                       ...     ...     ...  ...       ...    ...
1396               Yvon Mvogo    2022    6.65   28  6.650000    0.0
19833       Zakaria Aboukhlal    2022    6.66   23  6.660000    0.0
6226               Zeki Çelik    2022    6.66   26  6.780000    0.0
5840           Ángel Di María    2022    6.98   35  7.354615   0.58
12981                 Éderson    2022    6.62   23  6.680000  -0.12

[20507 rows x 6 columns]

In [276]:
#Forecasting player ratings between 2019-2025

for season in range(2019, 2025):
    
    previousPlayers = merged_rating_players_tree.loc[merged_rating_players_tree.Saison == season].copy()
    currentPlayers = merged_rating_players_tree.loc[merged_rating_players_tree.Saison == season+1].copy()
    futurePlayers = currentPlayers.copy()

    futurePlayers['Saison'] = currentPlayers['Saison'].values+1
    futurePlayers['Age'] = currentPlayers['Age'].values+1

    futurePlayers.drop(['Rating'], axis=1)

    li = []
    li.append(previousPlayers)
    li.append(currentPlayers)
    li.append(futurePlayers)

    df_combined = pd.concat(li)
    
    df_combined = df_combined.sort_values(['Saison', 'Name'])

    df_transformedPlayer_tree = df_combined.copy()
    df_transformedPlayer_tree['Last_Season_Rating'] = df_transformedPlayer_tree.groupby(['Name'])['Rating'].shift()
    df_transformedPlayer_tree['Last_Season_Diff'] = df_transformedPlayer_tree.groupby('Name')['Last_Season_Rating'].transform(Series.diff)
    df_transformedPlayer_tree = df_transformedPlayer_tree.dropna()
    
    df_transformedPlayer_tree = df_transformedPlayer_tree.loc[df_transformedPlayer_tree['Saison'] == season+2]
    
    currentSeasonDf = df_transformedPlayer_tree.drop(['Rating', 'Name', 'Saison'], axis=1)
    y_pred = lin_reg.predict(currentSeasonDf)

    #Attaching the predicted values to the original DF so that the cycle can continue 
    #~until the forecasting range comes to an end 
    ratings = ["{:.2f}".format(value) for value in y_pred.tolist()]
    df_transformedPlayer_tree['Rating'] = ratings
    df_transformedPlayer_tree['Rating'] = y_pred.round(2)
    df_transformedPlayer_tree = df_transformedPlayer_tree[['Name', 'Saison', 'Rating', 'Age', 'Mean', 'Growth']]
    merged_rating_players_tree = merged_rating_players_tree.append(df_transformedPlayer_tree, ignore_index=True)
    merged_rating_players_tree.drop_duplicates(subset=['Name', 'Saison'], keep='last', inplace=True)  # ajout de cette ligne
    merged_rating_players_tree = merged_rating_players_tree[merged_rating_players_tree['Rating'].notnull()].copy()
    merged_rating_players_tree['Rating'] = merged_rating_players_tree['Rating'].astype(float)

C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\2062377355.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players_tree = merged_rating_players_tree.append(df_transformedPlayer_tree, ignore_index=True)
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\2062377355.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players_tree = merged_rating_players_tree.append(df_transformedPlayer_tree, ignore_index=True)
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\2062377355.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players_tree = merged_rating_players_tree.append(df_transformedPlayer_tree, ignore_index=True)
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\2062377355.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players_tree = merged_rating_players_tree.append(df_transformedPlayer_tree, ignore_index=True)
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\2062377355.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players_tree = merged_rating_players_tree.append(df_transformedPlayer_tree, ignore_index=True)
C:\Users\lucas\AppData\Local\Temp\ipykernel_68892\2062377355.py:39: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  merged_rating_players_tree = merged_rating_players_tree.append(df_transformedPlayer_tree, ignore_index=True)

In [277]:
merged_rating_players_tree.loc[merged_rating_players_tree.Name == 'Kylian Mbappé']

                Name  Saison  Rating  Age      Mean Growth
12074  Kylian Mbappé    2016    7.22   18  7.772857    0.1
13696  Kylian Mbappé    2017    7.54   19  7.772857    0.1
15304  Kylian Mbappé    2018    8.00   20  7.772857    0.1
16634  Kylian Mbappé    2019    8.14   21  7.772857    0.1
17716  Kylian Mbappé    2020    7.68   22  7.772857    0.1
20506  Kylian Mbappé    2021    7.72   23  7.772857    0.1
21205  Kylian Mbappé    2022    7.74   24  7.772857    0.1
22048  Kylian Mbappé    2023    7.72   25  7.772857    0.1
22951  Kylian Mbappé    2024    7.69   26  7.772857    0.1
23854  Kylian Mbappé    2025    7.66   27  7.772857    0.1
24757  Kylian Mbappé    2026    7.64   28  7.772857    0.1

In [278]:
merged_rating_players.loc[merged_rating_players.Name == 'Lionel Messi']

               Name  Saison  Rating  Age    Mean Growth
896    Lionel Messi    2009    8.67   22  8.5575   1.07
2469   Lionel Messi    2010    8.76   23  8.5575   1.07
4070   Lionel Messi    2011    8.88   24  8.5575   1.07
5658   Lionel Messi    2012    8.83   25  8.5575   1.07
7240   Lionel Messi    2013    8.34   26  8.5575   1.07
8888   Lionel Messi    2014    8.84   27  8.5575   1.07
10528  Lionel Messi    2015    8.46   28  8.5575   1.07
12110  Lionel Messi    2016    8.47   29  8.5575   1.07
13726  Lionel Messi    2017    8.68   30  8.5575   1.07
15334  Lionel Messi    2018    8.48   31  8.5575   1.07
18535  Lionel Messi    2021    7.77   34  8.5575   1.07
19017  Lionel Messi    2022    8.51   35  8.5575   1.07
21172  Lionel Messi    2023    8.20   36  8.5575   1.07
22086  Lionel Messi    2024    8.08   37  8.5575   1.07
23000  Lionel Messi    2025    8.07   38  8.5575   1.07
23914  Lionel Messi    2026    8.05   39  8.5575   1.07

In [279]:
#write the DF to a csv file
merged_rating_players_tree.to_csv('Forecasted_Ratings_2022-2025_tree.csv', index = False)

Les deux morceaux de code effectuent des tâches différentes et ne peuvent donc pas être comparés directement. Le premier code utilise la régression linéaire pour prévoir les notes des joueurs pour chaque saison et évalue la performance en utilisant les mêmes métriques sur les données de test. Le deuxième code utilise un modèle d'arbre de décision pour prédire les notes de joueur et évalue la performance du modèle à l'aide de trois métriques : MSE, MAE et R2. Les deux approches sont différentes et ont leurs avantages et leurs inconvénients.

La première approche utilise une régression linéaire (linear_model.LinearRegression) pour prédire les notes des joueurs. Cette méthode est simple et facile à interpréter, mais peut être moins précise que des modèles plus complexes dans certains cas. Elle utilise également une validation croisée pour évaluer la performance du modèle et sélectionner les paramètres optimaux.

La deuxième approche utilise un modèle RandomForestRegressor pour prédire les notes des joueurs. Cette méthode peut être utile lorsque la relation entre les variables explicatives et la variable cible est non-linéaire et complexe. Elle utilise également une validation croisée pour évaluer la performance du modèle et sélectionner les paramètres optimaux.

Il est difficile de dire quelle approche est meilleure car cela dépend du contexte et des données spécifiques. Dans l'ensemble, la première approche peut être plus appropriée si la relation entre les variables est non-linéaire et complexe, tandis que la deuxième approche peut être plus appropriée si la relation entre les variables est linéaire et simple.

Si l'on compare les métriques d'erreur entre les différentes approches, on peut voir que le modèle RandomForestRegressor a une erreur moyenne plus faible (MSE : 0.03, MAE : 0.07) que les autres modèles sur les données de test. Cela suggère que le modèle RandomForestRegressor est plus précis dans ses prévisions que les autres modèles pour ces données. En outre, le modèle RandomForestRegressor a également un coefficient de détermination (R2) similaire à celui des autres modèles (R2 : 0.68), ce qui indique que le modèle est capable d'expliquer une grande partie de la variance des données observées. En considérant ces résultats, il est recommandé d'utiliser le modèle RandomForestRegressor pour la prédiction des notes des joueurs pour cette plage de temps (2010-2022).