# Preprocessing Whoscored

## Importation

In [1]:
import numpy as np
import pandas as pd

In [2]:
!wget https://raw.githubusercontent.com/lbenyamin/Skoot/main/Datasets/After_Concatenisation_Whoscored/Defensive_Whoscored_Data.csv
!wget https://raw.githubusercontent.com/lbenyamin/Skoot/main/Datasets/After_Concatenisation_Whoscored/Offensive_Whoscored_Data.csv
!wget https://raw.githubusercontent.com/lbenyamin/Skoot/main/Datasets/After_Concatenisation_Whoscored/Passing_Whoscored_Data.csv
!wget https://raw.githubusercontent.com/lbenyamin/Skoot/main/Datasets/After_Concatenisation_Whoscored/Summary_Whoscored_Data.csv
!wget https://raw.githubusercontent.com/lbenyamin/Skoot/main/Datasets/After_Scrap_FBref/FBREF_dataset_full.csv

--2023-03-23 17:47:34--  https://raw.githubusercontent.com/lbenyamin/Skoot/main/Datasets/After_Concatenisation_Whoscored/Defensive_Whoscored_Data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2989693 (2.9M) [text/plain]
Saving to: ‘Defensive_Whoscored_Data.csv’

Defensive_Whoscored 100%[===================>]   2.85M  --.-KB/s    in 0.07s

2023-03-23 17:47:34 (41.4 MB/s) - ‘Defensive_Whoscored_Data.csv’ saved [2989693/2989693]

--2023-03-23 17:47:34--  https://raw.githubusercontent.com/lbenyamin/Skoot/main/Datasets/After_Concatenisation_Whoscored/Offensive_Whoscored_Data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3099785 (3.0M) [text/plain]
Saving to: ‘Offensive_Whoscored_Data.csv’

Offensive_Whoscored 100%[===================>]   2.96M  --.-KB/s    in 0.07s

2023-03-23 17:47:35 (43.3 MB/s) - ‘Offensive_Whoscored_Data.csv’ saved [3099785/3099785]

--2023-03-23 17:47:35--  https://raw.githubusercontent.com/lbenyamin/Skoot/main/Datasets/After_Concatenisation_Whoscored/Passing_Whoscored_Data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2937458 (2.8M) [text/plain]
Saving to: ‘Passing_Whoscored_Data.csv’

Passing_Whoscored_D 100%[===================>]   2.80M  --.-KB/s    in 0.07s

2023-03-23 17:47:35 (41.2 MB/s) - ‘Passing_Whoscored_Data.csv’ saved [2937458/2937458]

--2023-03-23 17:47:35--  https://raw.githubusercontent.com/lbenyamin/Skoot/main/Datasets/After_Concatenisation_Whoscored/Summary_Whoscored_Data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2852235 (2.7M) [text/plain]
Saving to: ‘Summary_Whoscored_Data.csv’

Summary_Whoscored_D 100%[===================>]   2.72M  --.-KB/s    in 0.07s

2023-03-23 17:47:35 (40.7 MB/s) - ‘Summary_Whoscored_Data.csv’ saved [2852235/2852235]

--2023-03-23 17:47:36--  https://raw.githubusercontent.com/lbenyamin/Skoot/main/Datasets/After_Scrap_FBref/FBREF_dataset_full.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2893435 (2.8M) [text/plain]
Saving to: ‘FBREF_dataset_full.csv’

FBREF_dataset_full. 100%[===================>]   2.76M  --.-KB/s    in 0.07s

2023-03-23 17:47:36 (41.4 MB/s) - ‘FBREF_dataset_full.csv’ saved [2893435/2893435]

In [3]:
df_offensive = pd.read_csv('Offensive_Whoscored_Data.csv')
df_passing = pd.read_csv('Passing_Whoscored_Data.csv')
df_summary = pd.read_csv('Summary_Whoscored_Data.csv')
df_defensive = pd.read_csv('Defensive_Whoscored_Data.csv')

<ipython-input-3-0c3ca699a3f7>:1: DtypeWarning: Columns (6,7,8,9,10,11,12,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df_offensive = pd.read_csv('Offensive_Whoscored_Data.csv')
<ipython-input-3-0c3ca699a3f7>:2: DtypeWarning: Columns (6,7,8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_passing = pd.read_csv('Passing_Whoscored_Data.csv')
<ipython-input-3-0c3ca699a3f7>:3: DtypeWarning: Columns (6,7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_summary = pd.read_csv('Summary_Whoscored_Data.csv')
<ipython-input-3-0c3ca699a3f7>:4: DtypeWarning: Columns (6,7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_defensive = pd.read_csv('Defensive_Whoscored_Data.csv')

In [4]:
df_defensive

,Name,Team,Age,Position,Apps,Minutes,Tackles per game,Interceptions per game,Fouls per game,Offsides per game,Clearances per game,Dribbled past per game,Outfield blocks per game,Own goals,Rating,League,Saison
0,Arjen Robben,Bayern Munich,35,"M(CLR),FW",18(6),1779,0.6,0.5,0.9,-,-,0.7,-,-,8.18,Bundesliga,2009
1,Stefan Kießling,Bayer Leverkusen,35,FW,33,2924,1.2,0.7,2.5,-,0.3,0.5,0.1,-,7.79,Bundesliga,2009
2,Zvjezdan Misimovic,Wolfsburg,37,"AM(C),FW",31,2768,1.9,0.6,1.5,-,0.2,1.2,0.1,-,7.74,Bundesliga,2009
3,Edin Dzeko,Wolfsburg,33,FW,33(1),3003,0.5,0.1,1.9,-,0.9,0.2,0.1,-,7.73,Bundesliga,2009
4,Claudio Pizarro,Werder Bremen,40,"AM(C),FW",23(3),2130,1,0.7,2,-,0.7,0.4,0.2,-,7.63,Bundesliga,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32942,Mark Noble,West Ham,35,M(C),8(13),707,0.4,0.6,0.4,0.0,0.1,0.5,0.1,0,6.17,LaLiga,2020
32943,Rhian Brewster,Sheff Utd,22,FW,12(15),1125,0.3,0.2,0.7,0.0,0.1,0.4,0.1,0,6.17,LaLiga,2020
32944,Karlan Grant,West Brom,25,"AM(CL),FW",14(7),1133,0.2,0.2,0.4,0.0,0.7,0.1,0.0,0,6.15,LaLiga,2020
32945,Hal Robson-Kanu,West Brom,33,"AM(LR),FW",2(17),549,0.1,0.1,0.8,0.0,0.4,0.1,0.0,0,6.13,LaLiga,2020
32946,Romaine Sawyers,West Brom,31,M(CL),17(2),1490,1.6,0.9,0.9,0.1,0.5,1.5,0.2,1,6.12,LaLiga,2020

In [5]:
df_list = [df_defensive, df_passing, df_summary, df_offensive]

## Modification Position & Apps

### Position

In [6]:
df_dmc = df_offensive.loc[df_offensive["Position"] == "DMC"]
print(df_dmc)

                   Name                  Team  Age Position    Apps  Minutes  \
126           Ian Evatt             Blackpool   37      DMC   36(2)     3216
170     Tom Huddlestone             Tottenham   32      DMC   13(1)     1165
303       Jonathan Hogg           Aston Villa   30      DMC       5      397
355       George Thorne  West Bromwich Albion   26      DMC    0(1)       31
400        Glenn Whelan                 Stoke   35      DMC  14(15)     1348
...                 ...                   ...  ...      ...     ...      ...
32555    Godfred Donsah                Verona   23      DMC    0(1)       22
32573   Luca Mazzitelli                  Roma   23      DMC    0(1)       31
32578   Josip Radosevic                Napoli   25      DMC    0(8)      115
32580  Tiberio Guarente               Catania   33      DMC    8(5)      690
32631   Leandro Paredes                Chievo   25      DMC    0(1)       16

      Total goals Total Assists Shots per game Key passes per game  \
126             1             3            0.6                 0.4
170             2             2            2.1                 1.6
303             -             -              -                 0.6
355             -             -              1                   -
400             -             1            0.7                 0.5
...           ...           ...            ...                 ...
32555           -             -              -                   -
32573           -             -              -                   -
32578           -             -            0.1                 0.4
32580           -             -            0.6                 0.3
32631           -             -              -                   -

      Dribbles per game Fouled per game Offsides per game  \
126                 0.2             0.6               0.1
170                 0.3             0.5                 -
303                   -             0.8                 -
355                   -               1                 -
400                 0.1             0.6                 -
...                 ...             ...               ...
32555                 -               1                 -
32573                 -               1                 -
32578               0.1             0.3                 -
32580               0.3             1.3                 -
32631                 -               1                 -

      Dispossessed per game Bad control per game  Rating         League  \
126                     0.3                  0.6    7.00  PremierLeague
170                       1                  0.9    6.91  PremierLeague
303                     0.8                  1.4    6.67  PremierLeague
355                       1                    1    6.57  PremierLeague
400                     0.6                  0.3    6.49  PremierLeague
...                     ...                  ...     ...            ...
32555                     1                    -    6.31         SerieA
32573                     -                    2    6.24         SerieA
32578                     -                  0.1    6.23         SerieA
32580                   0.8                  0.3    6.22         SerieA
32631                     -                    2    6.04         SerieA

       Saison  Dribble
126      2010      NaN
170      2010      NaN
303      2010      NaN
355      2010      NaN
400      2010      NaN
...       ...      ...
32555    2013      NaN
32573    2013      NaN
32578    2013      NaN
32580    2013      NaN
32631    2013      NaN

[1140 rows x 19 columns]

In [7]:
positions = df_summary['Position'].unique()
print(positions)

['AM(CLR),FW' 'AM(LR),FW' 'DMC' 'GK' 'AM(R),FW' 'M(CLR),FW' 'D(R),M(R)'
 'M(CR),FW' 'AM(CL),FW' 'AM(CR),FW' 'AM(CLR)' 'Forward' 'D(R),M(CR)'
 'D(C)' 'Midfielder' 'D(CR),DMC' 'D(LR)' 'D(R),M(CLR)' 'M(LR),FW' 'D(L)'
 'D(CR)' 'D(LR),M(R)' 'D(CL)' 'M(C)' 'D(L),M(L)' 'AM(L),FW' 'M(CL)'
 'AM(CL)' 'AM(C),FW' 'D(R),M(L),FW' 'FW' 'D(CR),M(R)' 'AM(R)'
 'D(CLR),M(R)' 'Goalkeeper' 'D(C),M(C)' 'AM(C)' 'Defender' 'D(C),DMC'
 'D(R)' 'M(CLR)' 'D(LR),M(L)' 'D(L),M(CLR)' 'D(CL),DMC' 'D(L),M(CL)'
 'D(CLR)' 'AM(LR)' 'M(CR)' 'D(C),M(L)' 'AM(CR)' 'M(L)' 'M(CL),FW' 'AM(L)'
 'M(R)' 'D(LR),M(CLR)' 'M(R),FW' 'D(CR),M(C)' 'D(CL),M(L)' 'D(CL),M(C)'
 'M(L),FW' 'D(CLR),DMC' 'D(R),M(C)' 'D(LR),M(LR)' 'D(R),DMC' 'M(C),FW'
 'D(L),DMC' 'D(R),M(LR)' 'D(CR),M(CR)' 'D(CLR),M(C)' 'D(LR),DMC,M(R)'
 'D(R),DMC,M(R)' 'D(LR),M(CL)' 'D(L),DMC,M(L)' 'D(LR),M(CR)' 'D(L),M(C)'
 'D(CR),M(CL)' 'D(LR),M(C)' 'D(R),M(LR),FW' 'D(C),M(CR)' 'M(LR)'
 'DMC,M(L)' 'D(CLR),M(LR)' ' AM(LR),FW  ' ' AM(R),FW  ' ' AM(CL),FW  '
 ' M(CLR),FW  ' ' D(R),M(CLR)  ' ' M(C)  ' ' AM(CLR),FW  ' ' D(R),M(R)  '
 ' FW  ' ' M(LR)  ' ' AM(CLR)  ' ' M(CLR)  ' ' DMC  ' ' AM(L),FW  '
 ' D(C)  ' ' AM(LR)  ' ' AM(C),FW  ' ' D(CL),M(L)  ' ' D(CR),DMC  '
 ' D(LR),M(R)  ' ' D(CR),M(R)  ' ' D(CL),DMC  ' ' D(R),M(C)  '
 ' D(R),M(LR)  ' ' GK  ' ' M(CR),FW  ' ' DMC,M(R)  ' ' D(L),M(LR),FW  '
 ' AM(CR),FW  ' ' M(LR),FW  ' ' D(L),M(L)  ' ' D(L),M(LR)  ' ' M(CL)  '
 ' AM(C)  ' ' D(CR)  ' ' D(L),DMC  ' ' D(LR),DMC  ' ' AM(CL)  '
 ' D(L),M(CL)  ' ' M(CR)  ' ' D(C),DMC  ' ' D(C),M(C)  ' ' D(CLR),M(R)  '
 ' DMC,M(L)  ' ' D(CLR),M(L)  ' ' D(R),M(CLR),FW  ' ' D(R),M(CR)  '
 ' D(R)  ' ' D(L)  ' ' D(L),M(CLR),FW  ' ' D(CL)  ' ' D(CLR)  '
 ' D(CR),M(CR)  ' ' M(CL),FW  ' ' D(LR),M(L)  ' ' D(L),M(CLR)  '
 ' AM(CR)  ' ' D(CLR),M(LR)  ' ' M(L)  ' ' AM(L)  ' ' D(LR),M(LR)  '
 ' AM(R)  ' ' Midfielder  ' ' Forward  ' 'D(R),M(CLR),FW'
 'D(CLR),DMC,M(LR)' 'D(L),M(CR)' 'DMC,M(R)' 'D(CL),M(R)' 'D(C),DMC,M(R)'
 'D(C),M(CR),FW' 'D(C),M(C),FW' 'D(LR),DMC' ' D(R),M(CR),FW  '
 ' D(L),M(C)  ' ' M(C),FW  ' ' D(LR),M(CLR)  ' ' D(R),DMC  '
 ' D(CLR),DMC,M(R)  ' ' D(C),M(CLR)  ' 'D(C),M(R)' 'D(CL),DMC,M(L)'
 'D(C),M(CL),FW' 'D(C),M(R),FW' 'D(CR),DMC,M(L)' ' D(CR),DMC,M(R)  '
 ' M(L),FW  ' 'midfielder' 'D(CLR),M(L)' 'D(CR),M(LR)' 'D(C),M(CL)'
 'D(C),M(CLR),FW' 'D(R),DMC,M(LR)' 'D(C),FW' 'D(CLR),DMC,M(R)'
 'D(CR),M(CR),FW' ' D(CL),DMC,M(L)  ' ' D(CL),M(CL)  ' ' D(C),M(CL)  '
 ' D(R),DMC,M(R)  ' ' D(C),M(CR)  ' ' D(LR)  ' 'D(CLR),M(CR)'
 'D(CL),M(CR)' 'forward' 'D(R),M(CR),FW' 'D(L),M(LR)' 'D(C),M(CLR)'
 'D(L),M(LR),FW' 'D(C),DMC,M(L)' 'D(CL),M(CLR)' 'D(L),M(R)' 'D(CR),M(CLR)'
 'D(R),M(R),FW' ' D(LR),DMC,M(LR)  ' ' D(CLR),DMC  ' ' D(CR),M(C)  '
 ' D(R),M(R),FW  ' 'D(CL),FW' 'D(CL),M(CL)' 'D(R),M(L)' ' D(L),M(CR)  '
 ' M(R)  ' ' D(LR),M(CLR),FW  ' ' D(CLR),M(CLR)  ' ' D(L),DMC,M(L)  '
 ' D(R),DMC,M(LR)  ' ' D(LR),DMC,M(L)  ' ' D(LR),M(CL)  '
 ' D(C),M(C),FW  ' ' DMC,M(LR)  ' ' D(CR),M(LR)  ' ' D(C),M(L)  '
 ' M(R),FW  ' ' D(R),M(L)  ' ' D(LR),M(CR)  ']

In [8]:
import re

def remove_parentheses(text):
    return re.sub(r'\([^()]*\)', '', text)

texte = "AM(CLR),FW"
texte_sans_parentheses = remove_parentheses(texte)
print(texte_sans_parentheses)

AM,FW

In [9]:
df_offensive["Position"] = df_offensive["Position"].apply(remove_parentheses)
df_passing["Position"] = df_passing["Position"].apply(remove_parentheses)
df_summary["Position"] = df_summary["Position"].apply(remove_parentheses)
df_defensive["Position"] = df_defensive["Position"].apply(remove_parentheses)
positions = df_summary['Position'].unique()
print(positions)

['AM,FW' 'DMC' 'GK' 'M,FW' 'D,M' 'AM' 'Forward' 'D' 'Midfielder' 'D,DMC'
 'M' 'D,M,FW' 'FW' 'Goalkeeper' 'Defender' 'D,DMC,M' 'DMC,M' ' AM,FW  '
 ' M,FW  ' ' D,M  ' ' M  ' ' FW  ' ' AM  ' ' DMC  ' ' D  ' ' D,DMC  '
 ' GK  ' ' DMC,M  ' ' D,M,FW  ' ' Midfielder  ' ' Forward  ' ' D,DMC,M  '
 'midfielder' 'D,FW' 'forward']

In [10]:
for df in df_list:
    positions = df['Position'].unique()
    print(positions)

['M,FW' 'FW' 'AM,FW' 'M' 'D' 'D,M' 'Midfielder' 'D,DMC,M' 'D,DMC' 'GK'
 'AM' 'DMC,M' 'DMC' 'D,M,FW' 'Forward' 'Defender' 'Goalkeeper'
 'midfielder' ' M,FW  ' ' AM,FW  ' ' D,M  ' ' D,DMC  ' ' D  ' ' FW  '
 ' D,DMC,M  ' ' M  ' ' AM  ' ' DMC  ' ' D,M,FW  ' ' GK  ' ' Forward  '
 ' Midfielder  ' ' DMC,M  ' 'forward' 'D,FW']
['AM,FW' 'GK' 'M' 'M,FW' 'D' 'D,M' 'AM' 'DMC' 'FW' 'D,DMC' 'Defender'
 'Goalkeeper' 'D,DMC,M' 'DMC,M' 'Forward' 'Midfielder' ' AM,FW  ' ' D,M  '
 ' FW  ' ' M,FW  ' ' D,DMC  ' ' M  ' ' AM  ' ' DMC  ' ' D  ' ' GK  '
 ' D,M,FW  ' ' D,DMC,M  ' ' Forward  ' 'D,M,FW' 'midfielder' 'D,FW'
 ' DMC,M  ' ' Midfielder  ' 'forward']
['AM,FW' 'DMC' 'GK' 'M,FW' 'D,M' 'AM' 'Forward' 'D' 'Midfielder' 'D,DMC'
 'M' 'D,M,FW' 'FW' 'Goalkeeper' 'Defender' 'D,DMC,M' 'DMC,M' ' AM,FW  '
 ' M,FW  ' ' D,M  ' ' M  ' ' FW  ' ' AM  ' ' DMC  ' ' D  ' ' D,DMC  '
 ' GK  ' ' DMC,M  ' ' D,M,FW  ' ' Midfielder  ' ' Forward  ' ' D,DMC,M  '
 'midfielder' 'D,FW' 'forward']
['D,M' 'D' 'M,FW' 'AM,FW' 'FW' 'M' 'Goalkeeper' 'D,DMC' 'D,DMC,M' 'AM'
 'GK' 'DMC,M' 'D,M,FW' 'DMC' 'Defender' 'D,FW' 'Midfielder' 'Forward'
 ' FW  ' ' D,DMC,M  ' ' AM  ' ' M,FW  ' ' AM,FW  ' ' M  ' ' D  ' ' D,M  '
 ' D,DMC  ' ' D,M,FW  ' ' DMC  ' ' GK  ' ' DMC,M  ' ' Forward  '
 'midfielder' ' Midfielder  ' 'forward']

In [11]:
def replace_position(position):
    position = position.strip()  # Enlever les espaces autour de la position
    positions = position.split(",")  # Diviser la position en une liste de positions
    new_positions = []
    for pos in positions:
        if pos == 'M,FW' or pos == 'AM,FW' or pos =='AM':
            new_positions.append('Midfielder, Forward')
        elif pos == 'M':
            new_positions.append('Midfielder')
        elif pos == 'D,DMC,M' or pos == 'D,DMC' or pos == 'D,M':
            new_positions.append('Defender, Midfielder')
        elif pos == 'DMC':
            new_positions.append('Defender, Midfielder')
        elif pos == 'D': 
            new_positions.append('Defender')
        elif pos == 'GK':
            new_positions.append('Goalkeeper')
        elif pos == 'FW':
            new_positions.append('Forward')
        elif pos == 'D,FW': 
            new_positions.append('Defender, Forward')
        elif pos == 'D,M,FW': 
            new_positions.append('Defender, Midflieder, Forward')
        else:
            new_positions.append(pos)
    new_positions = list(set(new_positions))
    return ', '.join(sorted(new_positions))

In [12]:
def clean_positions(df):
    df['Position'] = df['Position'].apply(lambda x: x.strip())
    df['Position'].replace(['midfielder'], 'Midfielder', regex=False, inplace=True)
    df['Position'].replace(['forward'], 'Forward', regex=False, inplace=True)
    df['Position'] = df['Position'].apply(replace_position)
    df['Position'].replace(['Forward, Midfielder', 'Forward, Midfielder, Forward'], 'Midfielder, Forward', regex=False, inplace=True)
    df['Position'].replace(['Defender, Forward, Midfielder', 'Forward, Midfielder, Defender', '  Midfielder,  Defender, Forward'], 'Defender, Midfielder, Forward', regex=False, inplace=True)
    df['Position'].replace(['Defender, Midfielder, Midfielder', 'Defender, Defender, Midfielder', 'Defender, Defender, Midfielder, Midfielder'], 'Defender, Midfielder', regex=False, inplace=True)
    positions = df['Position'].unique()
    print(f"Positions in {df.name}: {positions}\n")
    
for df in df_list:
    df.name = df.columns[0]  # set the name of the dataframe as the name of the column
    clean_positions(df)

Positions in Name: ['Midfielder, Forward' 'Forward' 'Midfielder' 'Defender'
 'Defender, Midfielder' 'Goalkeeper' 'Defender, Midfielder, Forward'
 'Defender, Forward']

Positions in Name: ['Midfielder, Forward' 'Goalkeeper' 'Midfielder' 'Defender'
 'Defender, Midfielder' 'Forward' 'Defender, Midfielder, Forward'
 'Defender, Forward']

Positions in Name: ['Midfielder, Forward' 'Defender, Midfielder' 'Goalkeeper' 'Forward'
 'Defender' 'Midfielder' 'Defender, Midfielder, Forward'
 'Defender, Forward']

Positions in Name: ['Defender, Midfielder' 'Defender' 'Midfielder, Forward' 'Forward'
 'Midfielder' 'Goalkeeper' 'Defender, Midfielder, Forward'
 'Defender, Forward']

In [13]:
df_summary['Position'].unique()

array(['Midfielder, Forward', 'Defender, Midfielder', 'Goalkeeper',
       'Forward', 'Defender', 'Midfielder',
       'Defender, Midfielder, Forward', 'Defender, Forward'], dtype=object)

### Apps

In [14]:
def clean_apps(df_list):
    for df in df_list:
        if "Apps" in df.columns:
            # Créer deux nouvelles colonnes pour stocker les valeurs de départ et de remplacement
            df["Start Application"] = df["Apps"].str.extract(r"^(\d+)")
            df["Remplacement Application"] = df["Apps"].str.extract(r"\((\d+)\)$").fillna(0)

            # Transformer les colonnes en int
            df["Start Application"] = pd.to_numeric(df["Start Application"], errors="coerce")
            df["Remplacement Application"] = pd.to_numeric(df["Remplacement Application"], errors="coerce")
            # Supprimer la colonne originale
            df.drop(columns=["Apps"], inplace=True)

    return df_list

In [15]:
clean_apps(df_list)

[                     Name              Team  Age             Position  \
 0            Arjen Robben     Bayern Munich   35  Midfielder, Forward
 1         Stefan Kießling  Bayer Leverkusen   35              Forward
 2      Zvjezdan Misimovic         Wolfsburg   37  Midfielder, Forward
 3              Edin Dzeko         Wolfsburg   33              Forward
 4         Claudio Pizarro     Werder Bremen   40  Midfielder, Forward
 ...                   ...               ...  ...                  ...
 32942          Mark Noble          West Ham   35           Midfielder
 32943      Rhian Brewster         Sheff Utd   22              Forward
 32944        Karlan Grant         West Brom   25  Midfielder, Forward
 32945     Hal Robson-Kanu         West Brom   33  Midfielder, Forward
 32946     Romaine Sawyers         West Brom   31           Midfielder

        Minutes Tackles per game Interceptions per game Fouls per game  \
 0         1779              0.6                    0.5            0.9
 1         2924              1.2                    0.7            2.5
 2         2768              1.9                    0.6            1.5
 3         3003              0.5                    0.1            1.9
 4         2130                1                    0.7              2
 ...        ...              ...                    ...            ...
 32942      707              0.4                    0.6            0.4
 32943     1125              0.3                    0.2            0.7
 32944     1133              0.2                    0.2            0.4
 32945      549              0.1                    0.1            0.8
 32946     1490              1.6                    0.9            0.9

       Offsides per game Clearances per game Dribbled past per game  \
 0                     -                   -                    0.7
 1                     -                 0.3                    0.5
 2                     -                 0.2                    1.2
 3                     -                 0.9                    0.2
 4                     -                 0.7                    0.4
 ...                 ...                 ...                    ...
 32942               0.0                 0.1                    0.5
 32943               0.0                 0.1                    0.4
 32944               0.0                 0.7                    0.1
 32945               0.0                 0.4                    0.1
 32946               0.1                 0.5                    1.5

       Outfield blocks per game Own goals  Rating      League  Saison  \
 0                            -         -    8.18  Bundesliga    2009
 1                          0.1         -    7.79  Bundesliga    2009
 2                          0.1         -    7.74  Bundesliga    2009
 3                          0.1         -    7.73  Bundesliga    2009
 4                          0.2         -    7.63  Bundesliga    2009
 ...                        ...       ...     ...         ...     ...
 32942                      0.1         0    6.17      LaLiga    2020
 32943                      0.1         0    6.17      LaLiga    2020
 32944                      0.0         0    6.15      LaLiga    2020
 32945                      0.0         0    6.13      LaLiga    2020
 32946                      0.2         1    6.12      LaLiga    2020

        Start Application  Remplacement Application
 0                     18                         6
 1                     33                         0
 2                     31                         0
 3                     33                         1
 4                     23                         3
 ...                  ...                       ...
 32942                  8                        13
 32943                 12                        15
 32944                 14                         7
 32945                  2                        17
 32946                 17                         2

 [32947 rows x 18 columns],
                   Name                 Team  Age             Position  \
 0               Neymar            Barcelona   27  Midfielder, Forward
 1         Lionel Messi            Barcelona   32  Midfielder, Forward
 2          Lucas Pérez  Deportivo La Coruna   30  Midfielder, Forward
 3            Davy Roef  Deportivo La Coruna   25           Goalkeeper
 4          Luis Suárez            Barcelona   32  Midfielder, Forward
 ...                ...                  ...  ...                  ...
 32942       Mark Noble             West Ham   35           Midfielder
 32943   Rhian Brewster            Sheff Utd   22              Forward
 32944     Karlan Grant            West Brom   25  Midfielder, Forward
 32945  Hal Robson-Kanu            West Brom   33  Midfielder, Forward
 32946  Romaine Sawyers            West Brom   31           Midfielder

        Minutes Total Assists Key passes per game Passes per game  \
 0         2652            11                   3            50.7
 1         2833             9                 2.3            48.4
 2           90             1                   3              25
 3           90             -                   -              22
 4         2865            13                 1.8            24.9
 ...        ...           ...                 ...             ...
 32942      707             0                 0.2            20.5
 32943     1125             0                 0.4             7.7
 32944     1133             0                 0.1            10.3
 32945      549             0                 0.3             4.2
 32946     1490             0                 0.3            37.9

       Pass success percentage Crosses per game Long balls per game  \
 0                        76.5              2.2                 2.2
 1                        80.2              0.3                 2.7
 2                          84                3                   2
 3                        72.7                -                   5
 4                        74.8              0.2                 0.9
 ...                       ...              ...                 ...
 32942                    88.6              0.1                 1.3
 32943                    74.4              0.1                 0.3
 32944                    75.1              0.0                 0.1
 32945                    70.9              0.0                 0.1
 32946                    85.3              0.1                 2.2

       Through balls per game  Rating  League  Saison  Start Application  \
 0                        0.3    8.52  LaLiga    2016                 30
 1                        0.6    8.47  LaLiga    2016                 32
 2                          -    8.08  LaLiga    2016                  1
 3                          -    7.98  LaLiga    2016                  1
 4                        0.1    7.80  LaLiga    2016                 34
 ...                      ...     ...     ...     ...                ...
 32942                    0.0    6.17  LaLiga    2020                  8
 32943                    0.1    6.17  LaLiga    2020                 12
 32944                    0.0    6.15  LaLiga    2020                 14
 32945                    0.0    6.13  LaLiga    2020                  2
 32946                    0.1    6.12  LaLiga    2020                 17

        Remplacement Application
 0                             0
 1                             2
 2                             0
 3                             0
 4                             1
 ...                         ...
 32942                        13
 32943                        15
 32944                         7
 32945                        17
 32946                         2

 [32947 rows x 17 columns],
                     Name                 Team  Age              Position  \
 0                 Neymar  Paris Saint-Germain   27   Midfielder, Forward
 1          Kylian Mbappé  Paris Saint-Germain   20   Midfielder, Forward
 2          Téji Savanier                Nimes   27  Defender, Midfielder
 3           Jessy Moulin        Saint-Etienne   33            Goalkeeper
 4           Nicolas Pepe                Lille   24   Midfielder, Forward
 ...                  ...                  ...  ...                   ...
 32942      Nikola Vlasic             West Ham   25   Midfielder, Forward
 32943     Salomón Rondón              Everton   33               Forward
 32944      Ashley Barnes              Burnley   33   Midfielder, Forward
 32945  Andriy Yarmolenko             West Ham   33   Midfielder, Forward
 32946        Fábio Silva               Wolves   20               Forward

        Minutes Total Goals Total Assists Yellow cards Red cards  \
 0         1444          15             7            2         -
 1         2344          33             7            5         1
 2         2866           6            14            7         1
 3           90           -             -            -         -
 4         3332          22            11            1         -
 ...        ...         ...           ...          ...       ...
 32942      555           1             0            0         0
 32943      783           1             1            3         1
 32944      803           1             0            4         0
 32945      304           1             0            1         0
 32946      565           0             0            0         0

       Shots per game Pass success percentage Aerials won per game  \
 0                3.2                    81.1                  0.5
 1                4.3                    79.4                  0.1
 2                2.1                    71.4                  1.6
 3                  -                      85                    2
 4                3.1                    79.1                  1.2
 ...              ...                     ...                  ...
 32942            0.4                    80.8                  0.3
 32943            1.1                    62.4                  1.9
 32944            0.7                    63.7                  2.2
 32945            0.6                    77.2                  0.3
 32946            0.9                    68.4                  0.4

       Man of the match  Rating  League  Saison  Start Application  \
 0                    7    8.26  Ligue1    2018                 16
 1                    9    8.00  Ligue1    2018                 24
 2                    8    7.89  Ligue1    2018                 32
 3                    -    7.76  Ligue1    2018                  1
 4                   13    7.62  Ligue1    2018                 37
 ...                ...     ...     ...     ...                ...
 32942                0    6.22  LaLiga    2019                  6
 32943                0    6.19  LaLiga    2019                  8
 32944                0    6.18  LaLiga    2019                  8
 32945                0    6.15  LaLiga    2019                  1
 32946                0    6.09  LaLiga    2019                  6

        Remplacement Application
 0                             1
 1                             5
 2                             0
 3                             0
 4                             1
 ...                         ...
 32942                        13
 32943                        12
 32944                        15
 32945                        18
 32946                        16

 [32947 rows x 18 columns],
                     Name               Team  Age              Position  \
 0           James Milner        Aston Villa   33  Defender, Midfielder
 1      Javier Mascherano          Liverpool   35  Defender, Midfielder
 2         Paul Konchesky             Fulham   38              Defender
 3                   Nani  Manchester United   32   Midfielder, Forward
 4            Luis Suárez          Liverpool   32   Midfielder, Forward
 ...                  ...                ...  ...                   ...
 32947         Mark Noble           West Ham   35            Midfielder
 32948     Rhian Brewster          Sheff Utd   22               Forward
 32949       Karlan Grant          West Brom   25   Midfielder, Forward
 32950    Hal Robson-Kanu          West Brom   33   Midfielder, Forward
 32951    Romaine Sawyers          West Brom   31            Midfielder

        Minutes Total goals Total Assists Shots per game Key passes per game  \
 0           85           1             -              6                   2
 1           79           -             1              -                   1
 2           90           -             -              -                   4
 3         2674           9            14            4.1                 2.4
 4         1102           4             3            4.2                 1.9
 ...        ...         ...           ...            ...                 ...
 32947      707           0             0            0.0                 0.2
 32948     1125           0             0            0.9                 0.4
 32949     1133           1             0            0.8                 0.1
 32950      549           2             0            0.7                 0.3
 32951     1490           0             0            0.2                 0.3

       Dribbles per game Fouled per game Offsides per game  \
 0                     1               2                 -
 1                     1               1                 -
 2                     -               -                 -
 3                   2.5             1.9               0.1
 4                   3.2             2.8               0.8
 ...                 ...             ...               ...
 32947               NaN             0.4               0.0
 32948               NaN             0.5               0.1
 32949               NaN             0.6               0.3
 32950               NaN             0.5               0.2
 32951               NaN             0.7               0.0

       Dispossessed per game Bad control per game  Rating         League  \
 0                         3                    -    9.14  PremierLeague
 1                         1                    -    8.01  PremierLeague
 2                         -                    -    7.79  PremierLeague
 3                       2.4                    2    7.71  PremierLeague
 4                         2                    4    7.63  PremierLeague
 ...                     ...                  ...     ...            ...
 32947                   0.3                  0.2    6.17  PremierLeague
 32948                   0.7                  0.7    6.17  PremierLeague
 32949                   0.8                  1.5    6.15  PremierLeague
 32950                   0.8                  1.6    6.13  PremierLeague
 32951                   0.5                  0.7    6.12  PremierLeague

        Saison  Dribble  Start Application  Remplacement Application
 0        2010      NaN                  1                         0
 1        2010      NaN                  1                         0
 2        2010      NaN                  1                         0
 3        2010      NaN                 31                         2
 4        2010      NaN                 12                         1
 ...       ...      ...                ...                       ...
 32947    2020      0.1                  8                        13
 32948    2020      0.3                 12                        15
 32949    2020      0.4                 14                         7
 32950    2020      0.3                  2                        17
 32951    2020      0.4                 17                         2

 [32952 rows x 20 columns]]

In [16]:
df_defensive

,Name,Team,Age,Position,Minutes,Tackles per game,Interceptions per game,Fouls per game,Offsides per game,Clearances per game,Dribbled past per game,Outfield blocks per game,Own goals,Rating,League,Saison,Start Application,Remplacement Application
0,Arjen Robben,Bayern Munich,35,"Midfielder, Forward",1779,0.6,0.5,0.9,-,-,0.7,-,-,8.18,Bundesliga,2009,18,6
1,Stefan Kießling,Bayer Leverkusen,35,Forward,2924,1.2,0.7,2.5,-,0.3,0.5,0.1,-,7.79,Bundesliga,2009,33,0
2,Zvjezdan Misimovic,Wolfsburg,37,"Midfielder, Forward",2768,1.9,0.6,1.5,-,0.2,1.2,0.1,-,7.74,Bundesliga,2009,31,0
3,Edin Dzeko,Wolfsburg,33,Forward,3003,0.5,0.1,1.9,-,0.9,0.2,0.1,-,7.73,Bundesliga,2009,33,1
4,Claudio Pizarro,Werder Bremen,40,"Midfielder, Forward",2130,1,0.7,2,-,0.7,0.4,0.2,-,7.63,Bundesliga,2009,23,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32942,Mark Noble,West Ham,35,Midfielder,707,0.4,0.6,0.4,0.0,0.1,0.5,0.1,0,6.17,LaLiga,2020,8,13
32943,Rhian Brewster,Sheff Utd,22,Forward,1125,0.3,0.2,0.7,0.0,0.1,0.4,0.1,0,6.17,LaLiga,2020,12,15
32944,Karlan Grant,West Brom,25,"Midfielder, Forward",1133,0.2,0.2,0.4,0.0,0.7,0.1,0.0,0,6.15,LaLiga,2020,14,7
32945,Hal Robson-Kanu,West Brom,33,"Midfielder, Forward",549,0.1,0.1,0.8,0.0,0.4,0.1,0.0,0,6.13,LaLiga,2020,2,17
32946,Romaine Sawyers,West Brom,31,Midfielder,1490,1.6,0.9,0.9,0.1,0.5,1.5,0.2,1,6.12,LaLiga,2020,17,2

In [17]:
df_defensive.dtypes

Name                         object
Team                         object
Age                           int64
Position                     object
Minutes                       int64
Tackles per game             object
Interceptions per game       object
Fouls per game               object
Offsides per game            object
Clearances per game          object
Dribbled past per game       object
Outfield blocks per game     object
Own goals                    object
Rating                      float64
League                       object
Saison                        int64
Start Application             int64
Remplacement Application      int64
dtype: object

### Verification des données

In [18]:
df_dmc = df_offensive.loc[df_offensive["Position"] == "Defender, Midfielder"]
print(df_dmc)

                    Name            Team  Age              Position  Minutes  \
0           James Milner     Aston Villa   33  Defender, Midfielder       85
1      Javier Mascherano       Liverpool   35  Defender, Midfielder       79
10            Danny Rose       Tottenham   28  Defender, Midfielder      352
20           Ledley King       Tottenham   38  Defender, Midfielder      494
38         Marcos Alonso          Bolton   28  Defender, Midfielder      360
...                  ...             ...  ...                   ...      ...
32932     George Baldock       Sheff Utd   30  Defender, Midfielder     2789
32935    Jairo Riedewald  Crystal Palace   26  Defender, Midfielder     1819
32936        Jamal Lewis       Newcastle   25  Defender, Midfielder     1833
32944     John Lundstram       Sheff Utd   29  Defender, Midfielder     2032
32945    Ibrahima Diallo     Southampton   24  Defender, Midfielder     1012

      Total goals Total Assists Shots per game Key passes per game  \
0               1             -              6                   2
1               -             1              -                   1
10              -             1            0.5                 0.8
20              -             -            0.3                 0.2
38              -             -            0.5                   1
...           ...           ...            ...                 ...
32932           0             2            0.4                 0.6
32935           2             0            0.2                 0.4
32936           0             1            0.1                 0.6
32944           0             2            0.7                 0.7
32945           0             0            0.3                 0.4

      Dribbles per game Fouled per game Offsides per game  \
0                     1               2                 -
1                     1               1                 -
10                  2.5               3                 -
20                    -             0.7                 -
38                  0.3             2.5                 -
...                 ...             ...               ...
32932               NaN             0.7               0.3
32935               NaN             0.2               0.0
32936               NaN             0.7               0.0
32944               NaN             0.7               0.0
32945               NaN             0.5               0.0

      Dispossessed per game Bad control per game  Rating         League  \
0                         3                    -    9.14  PremierLeague
1                         1                    -    8.01  PremierLeague
10                      0.8                  1.8    7.53  PremierLeague
20                      0.2                  0.2    7.40  PremierLeague
38                      0.3                  0.8    7.31  PremierLeague
...                     ...                  ...     ...            ...
32932                   0.6                  1.0    6.35  PremierLeague
32935                   0.3                  0.8    6.34  PremierLeague
32936                   0.5                  0.7    6.34  PremierLeague
32944                   0.7                  1.0    6.23  PremierLeague
32945                   0.7                  0.9    6.22  PremierLeague

       Saison  Dribble  Start Application  Remplacement Application
0        2010      NaN                  1                         0
1        2010      NaN                  1                         0
10       2010      NaN                  4                         0
20       2010      NaN                  6                         0
38       2010      NaN                  4                         0
...       ...      ...                ...                       ...
32932    2020      0.5                 32                         0
32935    2020      0.4                 19                        14
32936    2020      0.5                 20                         4
32944    2020      0.5                 23                         5
32945    2020      0.5                 10                        12

[6987 rows x 20 columns]

In [19]:
df_offensive

,Name,Team,Age,Position,Minutes,Total goals,Total Assists,Shots per game,Key passes per game,Dribbles per game,Fouled per game,Offsides per game,Dispossessed per game,Bad control per game,Rating,League,Saison,Dribble,Start Application,Remplacement Application
0,James Milner,Aston Villa,33,"Defender, Midfielder",85,1,-,6,2,1,2,-,3,-,9.14,PremierLeague,2010,NaN,1,0
1,Javier Mascherano,Liverpool,35,"Defender, Midfielder",79,-,1,-,1,1,1,-,1,-,8.01,PremierLeague,2010,NaN,1,0
2,Paul Konchesky,Fulham,38,Defender,90,-,-,-,4,-,-,-,-,-,7.79,PremierLeague,2010,NaN,1,0
3,Nani,Manchester United,32,"Midfielder, Forward",2674,9,14,4.1,2.4,2.5,1.9,0.1,2.4,2,7.71,PremierLeague,2010,NaN,31,2
4,Luis Suárez,Liverpool,32,"Midfielder, Forward",1102,4,3,4.2,1.9,3.2,2.8,0.8,2,4,7.63,PremierLeague,2010,NaN,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32947,Mark Noble,West Ham,35,Midfielder,707,0,0,0.0,0.2,NaN,0.4,0.0,0.3,0.2,6.17,PremierLeague,2020,0.1,8,13
32948,Rhian Brewster,Sheff Utd,22,Forward,1125,0,0,0.9,0.4,NaN,0.5,0.1,0.7,0.7,6.17,PremierLeague,2020,0.3,12,15
32949,Karlan Grant,West Brom,25,"Midfielder, Forward",1133,1,0,0.8,0.1,NaN,0.6,0.3,0.8,1.5,6.15,PremierLeague,2020,0.4,14,7
32950,Hal Robson-Kanu,West Brom,33,"Midfielder, Forward",549,2,0,0.7,0.3,NaN,0.5,0.2,0.8,1.6,6.13,PremierLeague,2020,0.3,2,17
32951,Romaine Sawyers,West Brom,31,Midfielder,1490,0,0,0.2,0.3,NaN,0.7,0.0,0.5,0.7,6.12,PremierLeague,2020,0.4,17,2

In [20]:
saisons = df_offensive['Saison'].unique()
print(saisons)

[2010 2017 2015 2020 2021 2019 2011 2009 2014 2018 2013 2012 2022 2016]

In [21]:
df_passing

,Name,Team,Age,Position,Minutes,Total Assists,Key passes per game,Passes per game,Pass success percentage,Crosses per game,Long balls per game,Through balls per game,Rating,League,Saison,Start Application,Remplacement Application
0,Neymar,Barcelona,27,"Midfielder, Forward",2652,11,3,50.7,76.5,2.2,2.2,0.3,8.52,LaLiga,2016,30,0
1,Lionel Messi,Barcelona,32,"Midfielder, Forward",2833,9,2.3,48.4,80.2,0.3,2.7,0.6,8.47,LaLiga,2016,32,2
2,Lucas Pérez,Deportivo La Coruna,30,"Midfielder, Forward",90,1,3,25,84,3,2,-,8.08,LaLiga,2016,1,0
3,Davy Roef,Deportivo La Coruna,25,Goalkeeper,90,-,-,22,72.7,-,5,-,7.98,LaLiga,2016,1,0
4,Luis Suárez,Barcelona,32,"Midfielder, Forward",2865,13,1.8,24.9,74.8,0.2,0.9,0.1,7.80,LaLiga,2016,34,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32942,Mark Noble,West Ham,35,Midfielder,707,0,0.2,20.5,88.6,0.1,1.3,0.0,6.17,LaLiga,2020,8,13
32943,Rhian Brewster,Sheff Utd,22,Forward,1125,0,0.4,7.7,74.4,0.1,0.3,0.1,6.17,LaLiga,2020,12,15
32944,Karlan Grant,West Brom,25,"Midfielder, Forward",1133,0,0.1,10.3,75.1,0.0,0.1,0.0,6.15,LaLiga,2020,14,7
32945,Hal Robson-Kanu,West Brom,33,"Midfielder, Forward",549,0,0.3,4.2,70.9,0.0,0.1,0.0,6.13,LaLiga,2020,2,17
32946,Romaine Sawyers,West Brom,31,Midfielder,1490,0,0.3,37.9,85.3,0.1,2.2,0.1,6.12,LaLiga,2020,17,2

In [22]:
saisons = df_passing['Saison'].unique()
print(saisons)

[2016 2022 2010 2013 2009 2019 2017 2018 2014 2012 2011 2015 2021 2020]

In [23]:
df_summary

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,Pass success percentage,Aerials won per game,Man of the match,Rating,League,Saison,Start Application,Remplacement Application
0,Neymar,Paris Saint-Germain,27,"Midfielder, Forward",1444,15,7,2,-,3.2,81.1,0.5,7,8.26,Ligue1,2018,16,1
1,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2344,33,7,5,1,4.3,79.4,0.1,9,8.00,Ligue1,2018,24,5
2,Téji Savanier,Nimes,27,"Defender, Midfielder",2866,6,14,7,1,2.1,71.4,1.6,8,7.89,Ligue1,2018,32,0
3,Jessy Moulin,Saint-Etienne,33,Goalkeeper,90,-,-,-,-,-,85,2,-,7.76,Ligue1,2018,1,0
4,Nicolas Pepe,Lille,24,"Midfielder, Forward",3332,22,11,1,-,3.1,79.1,1.2,13,7.62,Ligue1,2018,37,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32942,Nikola Vlasic,West Ham,25,"Midfielder, Forward",555,1,0,0,0,0.4,80.8,0.3,0,6.22,LaLiga,2019,6,13
32943,Salomón Rondón,Everton,33,Forward,783,1,1,3,1,1.1,62.4,1.9,0,6.19,LaLiga,2019,8,12
32944,Ashley Barnes,Burnley,33,"Midfielder, Forward",803,1,0,4,0,0.7,63.7,2.2,0,6.18,LaLiga,2019,8,15
32945,Andriy Yarmolenko,West Ham,33,"Midfielder, Forward",304,1,0,1,0,0.6,77.2,0.3,0,6.15,LaLiga,2019,1,18
32946,Fábio Silva,Wolves,20,Forward,565,0,0,0,0,0.9,68.4,0.4,0,6.09,LaLiga,2019,6,16

In [24]:
saisons = df_passing['Saison'].unique()
print(saisons)

[2016 2022 2010 2013 2009 2019 2017 2018 2014 2012 2011 2015 2021 2020]

In [25]:
df_defensive

,Name,Team,Age,Position,Minutes,Tackles per game,Interceptions per game,Fouls per game,Offsides per game,Clearances per game,Dribbled past per game,Outfield blocks per game,Own goals,Rating,League,Saison,Start Application,Remplacement Application
0,Arjen Robben,Bayern Munich,35,"Midfielder, Forward",1779,0.6,0.5,0.9,-,-,0.7,-,-,8.18,Bundesliga,2009,18,6
1,Stefan Kießling,Bayer Leverkusen,35,Forward,2924,1.2,0.7,2.5,-,0.3,0.5,0.1,-,7.79,Bundesliga,2009,33,0
2,Zvjezdan Misimovic,Wolfsburg,37,"Midfielder, Forward",2768,1.9,0.6,1.5,-,0.2,1.2,0.1,-,7.74,Bundesliga,2009,31,0
3,Edin Dzeko,Wolfsburg,33,Forward,3003,0.5,0.1,1.9,-,0.9,0.2,0.1,-,7.73,Bundesliga,2009,33,1
4,Claudio Pizarro,Werder Bremen,40,"Midfielder, Forward",2130,1,0.7,2,-,0.7,0.4,0.2,-,7.63,Bundesliga,2009,23,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32942,Mark Noble,West Ham,35,Midfielder,707,0.4,0.6,0.4,0.0,0.1,0.5,0.1,0,6.17,LaLiga,2020,8,13
32943,Rhian Brewster,Sheff Utd,22,Forward,1125,0.3,0.2,0.7,0.0,0.1,0.4,0.1,0,6.17,LaLiga,2020,12,15
32944,Karlan Grant,West Brom,25,"Midfielder, Forward",1133,0.2,0.2,0.4,0.0,0.7,0.1,0.0,0,6.15,LaLiga,2020,14,7
32945,Hal Robson-Kanu,West Brom,33,"Midfielder, Forward",549,0.1,0.1,0.8,0.0,0.4,0.1,0.0,0,6.13,LaLiga,2020,2,17
32946,Romaine Sawyers,West Brom,31,Midfielder,1490,1.6,0.9,0.9,0.1,0.5,1.5,0.2,1,6.12,LaLiga,2020,17,2

In [26]:
saisons = df_passing['Saison'].unique()
print(saisons)

[2016 2022 2010 2013 2009 2019 2017 2018 2014 2012 2011 2015 2021 2020]

#### Nombre de Lignes nulles par colonnes

In [27]:
# Liste des valeurs manquantes à remplacer
missing_values = ['', ' ', '-', '--', 'NA', 'N/A', 'n/a', 'NaN', 'nan', '.', '..', '...']

# Remplacer les valeurs manquantes par NaN
df_defensive_null = df_defensive.replace(missing_values, pd.NA)
# Compter le nombre de valeurs nulles pour chaque colonne
null_counts = df_defensive_null.isna().sum()

# Afficher le nombre de valeurs nulles pour chaque colonne
print(null_counts)

Name                            0
Team                            0
Age                             0
Position                        0
Minutes                         0
Tackles per game             3590
Interceptions per game       4272
Fouls per game               3498
Offsides per game           17574
Clearances per game          3368
Dribbled past per game       4197
Outfield blocks per game    11347
Own goals                   25860
Rating                          0
League                          0
Saison                          0
Start Application               0
Remplacement Application        0
dtype: int64

In [28]:
df_defensive_null

,Name,Team,Age,Position,Minutes,Tackles per game,Interceptions per game,Fouls per game,Offsides per game,Clearances per game,Dribbled past per game,Outfield blocks per game,Own goals,Rating,League,Saison,Start Application,Remplacement Application
0,Arjen Robben,Bayern Munich,35,"Midfielder, Forward",1779,0.6,0.5,0.9,<NA>,<NA>,0.7,<NA>,<NA>,8.18,Bundesliga,2009,18,6
1,Stefan Kießling,Bayer Leverkusen,35,Forward,2924,1.2,0.7,2.5,<NA>,0.3,0.5,0.1,<NA>,7.79,Bundesliga,2009,33,0
2,Zvjezdan Misimovic,Wolfsburg,37,"Midfielder, Forward",2768,1.9,0.6,1.5,<NA>,0.2,1.2,0.1,<NA>,7.74,Bundesliga,2009,31,0
3,Edin Dzeko,Wolfsburg,33,Forward,3003,0.5,0.1,1.9,<NA>,0.9,0.2,0.1,<NA>,7.73,Bundesliga,2009,33,1
4,Claudio Pizarro,Werder Bremen,40,"Midfielder, Forward",2130,1,0.7,2,<NA>,0.7,0.4,0.2,<NA>,7.63,Bundesliga,2009,23,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32942,Mark Noble,West Ham,35,Midfielder,707,0.4,0.6,0.4,0.0,0.1,0.5,0.1,0,6.17,LaLiga,2020,8,13
32943,Rhian Brewster,Sheff Utd,22,Forward,1125,0.3,0.2,0.7,0.0,0.1,0.4,0.1,0,6.17,LaLiga,2020,12,15
32944,Karlan Grant,West Brom,25,"Midfielder, Forward",1133,0.2,0.2,0.4,0.0,0.7,0.1,0.0,0,6.15,LaLiga,2020,14,7
32945,Hal Robson-Kanu,West Brom,33,"Midfielder, Forward",549,0.1,0.1,0.8,0.0,0.4,0.1,0.0,0,6.13,LaLiga,2020,2,17
32946,Romaine Sawyers,West Brom,31,Midfielder,1490,1.6,0.9,0.9,0.1,0.5,1.5,0.2,1,6.12,LaLiga,2020,17,2

In [29]:
# Liste des valeurs manquantes à remplacer
missing_values = ['', ' ', '-', '--', 'NA', 'N/A', 'n/a', 'NaN', 'nan', '.', '..', '...']

# Remplacer les valeurs manquantes par NaN
df_passing_null = df_passing.replace(missing_values, pd.NA)
# Compter le nombre de valeurs nulles pour chaque colonne
null_counts = df_passing_null.isna().sum()

# Afficher le nombre de valeurs nulles pour chaque colonne
print(null_counts)

Name                            0
Team                            0
Age                             0
Position                        0
Minutes                         0
Total Assists               14551
Key passes per game          5114
Passes per game               139
Pass success percentage       207
Crosses per game            11489
Long balls per game          2500
Through balls per game      19835
Rating                          0
League                          0
Saison                          0
Start Application               0
Remplacement Application        0
dtype: int64

In [30]:
df_passing_null

,Name,Team,Age,Position,Minutes,Total Assists,Key passes per game,Passes per game,Pass success percentage,Crosses per game,Long balls per game,Through balls per game,Rating,League,Saison,Start Application,Remplacement Application
0,Neymar,Barcelona,27,"Midfielder, Forward",2652,11,3,50.7,76.5,2.2,2.2,0.3,8.52,LaLiga,2016,30,0
1,Lionel Messi,Barcelona,32,"Midfielder, Forward",2833,9,2.3,48.4,80.2,0.3,2.7,0.6,8.47,LaLiga,2016,32,2
2,Lucas Pérez,Deportivo La Coruna,30,"Midfielder, Forward",90,1,3,25,84,3,2,<NA>,8.08,LaLiga,2016,1,0
3,Davy Roef,Deportivo La Coruna,25,Goalkeeper,90,<NA>,<NA>,22,72.7,<NA>,5,<NA>,7.98,LaLiga,2016,1,0
4,Luis Suárez,Barcelona,32,"Midfielder, Forward",2865,13,1.8,24.9,74.8,0.2,0.9,0.1,7.80,LaLiga,2016,34,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32942,Mark Noble,West Ham,35,Midfielder,707,0,0.2,20.5,88.6,0.1,1.3,0.0,6.17,LaLiga,2020,8,13
32943,Rhian Brewster,Sheff Utd,22,Forward,1125,0,0.4,7.7,74.4,0.1,0.3,0.1,6.17,LaLiga,2020,12,15
32944,Karlan Grant,West Brom,25,"Midfielder, Forward",1133,0,0.1,10.3,75.1,0.0,0.1,0.0,6.15,LaLiga,2020,14,7
32945,Hal Robson-Kanu,West Brom,33,"Midfielder, Forward",549,0,0.3,4.2,70.9,0.0,0.1,0.0,6.13,LaLiga,2020,2,17
32946,Romaine Sawyers,West Brom,31,Midfielder,1490,0,0.3,37.9,85.3,0.1,2.2,0.1,6.12,LaLiga,2020,17,2

In [31]:
# Liste des valeurs manquantes à remplacer
missing_values = ['', ' ', '-', '--', 'NA', 'N/A', 'n/a', 'NaN', 'nan', '.', '..', '...']

# Remplacer les valeurs manquantes par NaN
df_offensive_null = df_offensive.replace(missing_values, pd.NA)
# Compter le nombre de valeurs nulles pour chaque colonne
null_counts = df_offensive_null.isna().sum()

# Afficher le nombre de valeurs nulles pour chaque colonne
print(null_counts)

Name                            0
Team                            0
Age                             0
Position                        0
Minutes                         0
Total goals                 14288
Total Assists               14551
Shots per game               4842
Key passes per game          5114
Dribbles per game           11655
Fouled per game              3016
Offsides per game           15245
Dispossessed per game        4890
Bad control per game         6277
Rating                          0
League                          0
Saison                          0
Dribble                     27193
Start Application               0
Remplacement Application        0
dtype: int64

In [32]:
df_offensive_null

,Name,Team,Age,Position,Minutes,Total goals,Total Assists,Shots per game,Key passes per game,Dribbles per game,Fouled per game,Offsides per game,Dispossessed per game,Bad control per game,Rating,League,Saison,Dribble,Start Application,Remplacement Application
0,James Milner,Aston Villa,33,"Defender, Midfielder",85,1,<NA>,6,2,1,2,<NA>,3,<NA>,9.14,PremierLeague,2010,NaN,1,0
1,Javier Mascherano,Liverpool,35,"Defender, Midfielder",79,<NA>,1,<NA>,1,1,1,<NA>,1,<NA>,8.01,PremierLeague,2010,NaN,1,0
2,Paul Konchesky,Fulham,38,Defender,90,<NA>,<NA>,<NA>,4,<NA>,<NA>,<NA>,<NA>,<NA>,7.79,PremierLeague,2010,NaN,1,0
3,Nani,Manchester United,32,"Midfielder, Forward",2674,9,14,4.1,2.4,2.5,1.9,0.1,2.4,2,7.71,PremierLeague,2010,NaN,31,2
4,Luis Suárez,Liverpool,32,"Midfielder, Forward",1102,4,3,4.2,1.9,3.2,2.8,0.8,2,4,7.63,PremierLeague,2010,NaN,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32947,Mark Noble,West Ham,35,Midfielder,707,0,0,0.0,0.2,NaN,0.4,0.0,0.3,0.2,6.17,PremierLeague,2020,0.1,8,13
32948,Rhian Brewster,Sheff Utd,22,Forward,1125,0,0,0.9,0.4,NaN,0.5,0.1,0.7,0.7,6.17,PremierLeague,2020,0.3,12,15
32949,Karlan Grant,West Brom,25,"Midfielder, Forward",1133,1,0,0.8,0.1,NaN,0.6,0.3,0.8,1.5,6.15,PremierLeague,2020,0.4,14,7
32950,Hal Robson-Kanu,West Brom,33,"Midfielder, Forward",549,2,0,0.7,0.3,NaN,0.5,0.2,0.8,1.6,6.13,PremierLeague,2020,0.3,2,17
32951,Romaine Sawyers,West Brom,31,Midfielder,1490,0,0,0.2,0.3,NaN,0.7,0.0,0.5,0.7,6.12,PremierLeague,2020,0.4,17,2

In [33]:
# Liste des valeurs manquantes à remplacer
missing_values = ['', ' ', '-', '--', 'NA', 'N/A', 'n/a', 'NaN', 'nan', '.', '..', '...']

# Remplacer les valeurs manquantes par NaN
df_summary_null = df_summary.replace(missing_values, pd.NA)
# Compter le nombre de valeurs nulles pour chaque colonne
null_counts = df_summary_null.isna().sum()

# Afficher le nombre de valeurs nulles pour chaque colonne
print(null_counts)

Name                            0
Team                            0
Age                             0
Position                        0
Minutes                         0
Total Goals                 14288
Total Assists               14551
Yellow cards                 7388
Red cards                   23431
Shots per game               4842
Pass success percentage       207
Aerials won per game         3523
Man of the match            17808
Rating                          0
League                          0
Saison                          0
Start Application               0
Remplacement Application        0
dtype: int64

In [34]:
df_summary_null

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,Pass success percentage,Aerials won per game,Man of the match,Rating,League,Saison,Start Application,Remplacement Application
0,Neymar,Paris Saint-Germain,27,"Midfielder, Forward",1444,15,7,2,<NA>,3.2,81.1,0.5,7,8.26,Ligue1,2018,16,1
1,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2344,33,7,5,1,4.3,79.4,0.1,9,8.00,Ligue1,2018,24,5
2,Téji Savanier,Nimes,27,"Defender, Midfielder",2866,6,14,7,1,2.1,71.4,1.6,8,7.89,Ligue1,2018,32,0
3,Jessy Moulin,Saint-Etienne,33,Goalkeeper,90,<NA>,<NA>,<NA>,<NA>,<NA>,85,2,<NA>,7.76,Ligue1,2018,1,0
4,Nicolas Pepe,Lille,24,"Midfielder, Forward",3332,22,11,1,<NA>,3.1,79.1,1.2,13,7.62,Ligue1,2018,37,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32942,Nikola Vlasic,West Ham,25,"Midfielder, Forward",555,1,0,0,0,0.4,80.8,0.3,0,6.22,LaLiga,2019,6,13
32943,Salomón Rondón,Everton,33,Forward,783,1,1,3,1,1.1,62.4,1.9,0,6.19,LaLiga,2019,8,12
32944,Ashley Barnes,Burnley,33,"Midfielder, Forward",803,1,0,4,0,0.7,63.7,2.2,0,6.18,LaLiga,2019,8,15
32945,Andriy Yarmolenko,West Ham,33,"Midfielder, Forward",304,1,0,1,0,0.6,77.2,0.3,0,6.15,LaLiga,2019,1,18
32946,Fábio Silva,Wolves,20,Forward,565,0,0,0,0,0.9,68.4,0.4,0,6.09,LaLiga,2019,6,16

#### Type de données par colonnes

In [35]:
# Type de données des colonnes de df_defensive
print(df_defensive.dtypes)

Name                         object
Team                         object
Age                           int64
Position                     object
Minutes                       int64
Tackles per game             object
Interceptions per game       object
Fouls per game               object
Offsides per game            object
Clearances per game          object
Dribbled past per game       object
Outfield blocks per game     object
Own goals                    object
Rating                      float64
League                       object
Saison                        int64
Start Application             int64
Remplacement Application      int64
dtype: object

In [36]:
# Type de données des colonnes de df_summary
print(df_summary.dtypes)

Name                         object
Team                         object
Age                           int64
Position                     object
Minutes                       int64
Total Goals                  object
Total Assists                object
Yellow cards                 object
Red cards                    object
Shots per game               object
Pass success percentage      object
Aerials won per game         object
Man of the match             object
Rating                      float64
League                       object
Saison                        int64
Start Application             int64
Remplacement Application      int64
dtype: object

In [37]:
# Type de données des colonnes de df_offensive
print(df_offensive.dtypes)

Name                         object
Team                         object
Age                           int64
Position                     object
Minutes                       int64
Total goals                  object
Total Assists                object
Shots per game               object
Key passes per game          object
Dribbles per game            object
Fouled per game              object
Offsides per game            object
Dispossessed per game        object
Bad control per game         object
Rating                      float64
League                       object
Saison                        int64
Dribble                     float64
Start Application             int64
Remplacement Application      int64
dtype: object

In [38]:
# Type de données des colonnes de df_passing
print(df_passing.dtypes)

Name                         object
Team                         object
Age                           int64
Position                     object
Minutes                       int64
Total Assists                object
Key passes per game          object
Passes per game              object
Pass success percentage      object
Crosses per game             object
Long balls per game          object
Through balls per game       object
Rating                      float64
League                       object
Saison                        int64
Start Application             int64
Remplacement Application      int64
dtype: object

#### dtype modification

In [39]:
# liste des colonnes qui doivent être exclues
exclude_cols = ['Name', 'Team', 'Position', 'League']

# boucle à travers toutes les dataframes
for df in df_list:
    # boucle à travers toutes les colonnes de chaque dataframe
    for col in df.columns:
        # vérifier si la colonne doit être convertie en float64
        if col not in exclude_cols and df[col].dtype == 'object':
            # convertir la colonne en float64
            df[col] = pd.to_numeric(df[col], errors='coerce')
            
    print(df.dtypes)

Name                         object
Team                         object
Age                           int64
Position                     object
Minutes                       int64
Tackles per game            float64
Interceptions per game      float64
Fouls per game              float64
Offsides per game           float64
Clearances per game         float64
Dribbled past per game      float64
Outfield blocks per game    float64
Own goals                   float64
Rating                      float64
League                       object
Saison                        int64
Start Application             int64
Remplacement Application      int64
dtype: object
Name                         object
Team                         object
Age                           int64
Position                     object
Minutes                       int64
Total Assists               float64
Key passes per game         float64
Passes per game             float64
Pass success percentage     float64
Crosses per game            float64
Long balls per game         float64
Through balls per game      float64
Rating                      float64
League                       object
Saison                        int64
Start Application             int64
Remplacement Application      int64
dtype: object
Name                         object
Team                         object
Age                           int64
Position                     object
Minutes                       int64
Total Goals                 float64
Total Assists               float64
Yellow cards                float64
Red cards                   float64
Shots per game              float64
Pass success percentage     float64
Aerials won per game        float64
Man of the match            float64
Rating                      float64
League                       object
Saison                        int64
Start Application             int64
Remplacement Application      int64
dtype: object
Name                         object
Team                         object
Age                           int64
Position                     object
Minutes                       int64
Total goals                 float64
Total Assists               float64
Shots per game              float64
Key passes per game         float64
Dribbles per game           float64
Fouled per game             float64
Offsides per game           float64
Dispossessed per game       float64
Bad control per game        float64
Rating                      float64
League                       object
Saison                        int64
Dribble                     float64
Start Application             int64
Remplacement Application      int64
dtype: object

In [40]:
df_summary

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,Pass success percentage,Aerials won per game,Man of the match,Rating,League,Saison,Start Application,Remplacement Application
0,Neymar,Paris Saint-Germain,27,"Midfielder, Forward",1444,15.0,7.0,2.0,NaN,3.2,81.1,0.5,7.0,8.26,Ligue1,2018,16,1
1,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2344,33.0,7.0,5.0,1.0,4.3,79.4,0.1,9.0,8.00,Ligue1,2018,24,5
2,Téji Savanier,Nimes,27,"Defender, Midfielder",2866,6.0,14.0,7.0,1.0,2.1,71.4,1.6,8.0,7.89,Ligue1,2018,32,0
3,Jessy Moulin,Saint-Etienne,33,Goalkeeper,90,NaN,NaN,NaN,NaN,NaN,85.0,2.0,NaN,7.76,Ligue1,2018,1,0
4,Nicolas Pepe,Lille,24,"Midfielder, Forward",3332,22.0,11.0,1.0,NaN,3.1,79.1,1.2,13.0,7.62,Ligue1,2018,37,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32942,Nikola Vlasic,West Ham,25,"Midfielder, Forward",555,1.0,0.0,0.0,0.0,0.4,80.8,0.3,0.0,6.22,LaLiga,2019,6,13
32943,Salomón Rondón,Everton,33,Forward,783,1.0,1.0,3.0,1.0,1.1,62.4,1.9,0.0,6.19,LaLiga,2019,8,12
32944,Ashley Barnes,Burnley,33,"Midfielder, Forward",803,1.0,0.0,4.0,0.0,0.7,63.7,2.2,0.0,6.18,LaLiga,2019,8,15
32945,Andriy Yarmolenko,West Ham,33,"Midfielder, Forward",304,1.0,0.0,1.0,0.0,0.6,77.2,0.3,0.0,6.15,LaLiga,2019,1,18
32946,Fábio Silva,Wolves,20,Forward,565,0.0,0.0,0.0,0.0,0.9,68.4,0.4,0.0,6.09,LaLiga,2019,6,16

### Modification des NaN par des 0

In [41]:
for df in df_list:
    df.fillna(0, inplace=True)

In [42]:
df_summary

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,Pass success percentage,Aerials won per game,Man of the match,Rating,League,Saison,Start Application,Remplacement Application
0,Neymar,Paris Saint-Germain,27,"Midfielder, Forward",1444,15.0,7.0,2.0,0.0,3.2,81.1,0.5,7.0,8.26,Ligue1,2018,16,1
1,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2344,33.0,7.0,5.0,1.0,4.3,79.4,0.1,9.0,8.00,Ligue1,2018,24,5
2,Téji Savanier,Nimes,27,"Defender, Midfielder",2866,6.0,14.0,7.0,1.0,2.1,71.4,1.6,8.0,7.89,Ligue1,2018,32,0
3,Jessy Moulin,Saint-Etienne,33,Goalkeeper,90,0.0,0.0,0.0,0.0,0.0,85.0,2.0,0.0,7.76,Ligue1,2018,1,0
4,Nicolas Pepe,Lille,24,"Midfielder, Forward",3332,22.0,11.0,1.0,0.0,3.1,79.1,1.2,13.0,7.62,Ligue1,2018,37,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32942,Nikola Vlasic,West Ham,25,"Midfielder, Forward",555,1.0,0.0,0.0,0.0,0.4,80.8,0.3,0.0,6.22,LaLiga,2019,6,13
32943,Salomón Rondón,Everton,33,Forward,783,1.0,1.0,3.0,1.0,1.1,62.4,1.9,0.0,6.19,LaLiga,2019,8,12
32944,Ashley Barnes,Burnley,33,"Midfielder, Forward",803,1.0,0.0,4.0,0.0,0.7,63.7,2.2,0.0,6.18,LaLiga,2019,8,15
32945,Andriy Yarmolenko,West Ham,33,"Midfielder, Forward",304,1.0,0.0,1.0,0.0,0.6,77.2,0.3,0.0,6.15,LaLiga,2019,1,18
32946,Fábio Silva,Wolves,20,Forward,565,0.0,0.0,0.0,0.0,0.9,68.4,0.4,0.0,6.09,LaLiga,2019,6,16

In [43]:
def convert_to_int(df_list, exclude_cols=[]):
    for df in df_list:
        for col in df.columns:
            if col not in exclude_cols:
                try:
                    # Vérifier si toutes les valeurs décimales de la colonne sont des zéros
                    if all(pd.to_numeric(df[col], errors='coerce').fillna(0) % 1 == 0):
                        df[col] = pd.to_numeric(df[col], downcast='integer')
                except ValueError:
                    pass

In [44]:
convert_to_int(df_list)

for df in df_list:
    print(df.dtypes)

Name                         object
Team                         object
Age                            int8
Position                     object
Minutes                       int16
Tackles per game            float64
Interceptions per game      float64
Fouls per game              float64
Offsides per game           float64
Clearances per game         float64
Dribbled past per game      float64
Outfield blocks per game    float64
Own goals                      int8
Rating                      float64
League                       object
Saison                        int16
Start Application              int8
Remplacement Application       int8
dtype: object
Name                         object
Team                         object
Age                            int8
Position                     object
Minutes                       int16
Total Assists                  int8
Key passes per game         float64
Passes per game             float64
Pass success percentage     float64
Crosses per game            float64
Long balls per game         float64
Through balls per game      float64
Rating                      float64
League                       object
Saison                        int16
Start Application              int8
Remplacement Application       int8
dtype: object
Name                         object
Team                         object
Age                            int8
Position                     object
Minutes                       int16
Total Goals                    int8
Total Assists                  int8
Yellow cards                   int8
Red cards                      int8
Shots per game              float64
Pass success percentage     float64
Aerials won per game        float64
Man of the match               int8
Rating                      float64
League                       object
Saison                        int16
Start Application              int8
Remplacement Application       int8
dtype: object
Name                         object
Team                         object
Age                            int8
Position                     object
Minutes                       int16
Total goals                    int8
Total Assists                  int8
Shots per game              float64
Key passes per game         float64
Dribbles per game           float64
Fouled per game             float64
Offsides per game           float64
Dispossessed per game       float64
Bad control per game        float64
Rating                      float64
League                       object
Saison                        int16
Dribble                     float64
Start Application              int8
Remplacement Application       int8
dtype: object

In [45]:
df_summary

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,Pass success percentage,Aerials won per game,Man of the match,Rating,League,Saison,Start Application,Remplacement Application
0,Neymar,Paris Saint-Germain,27,"Midfielder, Forward",1444,15,7,2,0,3.2,81.1,0.5,7,8.26,Ligue1,2018,16,1
1,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2344,33,7,5,1,4.3,79.4,0.1,9,8.00,Ligue1,2018,24,5
2,Téji Savanier,Nimes,27,"Defender, Midfielder",2866,6,14,7,1,2.1,71.4,1.6,8,7.89,Ligue1,2018,32,0
3,Jessy Moulin,Saint-Etienne,33,Goalkeeper,90,0,0,0,0,0.0,85.0,2.0,0,7.76,Ligue1,2018,1,0
4,Nicolas Pepe,Lille,24,"Midfielder, Forward",3332,22,11,1,0,3.1,79.1,1.2,13,7.62,Ligue1,2018,37,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32942,Nikola Vlasic,West Ham,25,"Midfielder, Forward",555,1,0,0,0,0.4,80.8,0.3,0,6.22,LaLiga,2019,6,13
32943,Salomón Rondón,Everton,33,Forward,783,1,1,3,1,1.1,62.4,1.9,0,6.19,LaLiga,2019,8,12
32944,Ashley Barnes,Burnley,33,"Midfielder, Forward",803,1,0,4,0,0.7,63.7,2.2,0,6.18,LaLiga,2019,8,15
32945,Andriy Yarmolenko,West Ham,33,"Midfielder, Forward",304,1,0,1,0,0.6,77.2,0.3,0,6.15,LaLiga,2019,1,18
32946,Fábio Silva,Wolves,20,Forward,565,0,0,0,0,0.9,68.4,0.4,0,6.09,LaLiga,2019,6,16

### Supprimer les lignes qui fossent la prédictions des valeurs

In [46]:
# Supprimer les joueurs qui ont joué moins de 20 matchs en début de saison ou ceux qui ont un remplacement de moins de 20 matchs
df_offensive = df_offensive[(df_offensive['Start Application'] >= 10) | (df_offensive['Remplacement Application'] >= 20)]

In [47]:
# Supprimer les joueurs qui ont joué moins de 20 matchs en début de saison ou ceux qui ont un remplacement de moins de 20 matchs
df_defensive = df_defensive[(df_defensive['Start Application'] >= 10) | (df_defensive['Remplacement Application'] >= 20)]

In [48]:
# Supprimer les joueurs qui ont joué moins de 20 matchs en début de saison ou ceux qui ont un remplacement de moins de 20 matchs
df_summary = df_summary[(df_summary['Start Application'] >=10) | (df_summary['Remplacement Application'] >= 20)]

In [49]:
# Supprimer les joueurs qui ont joué moins de 20 matchs en début de saison ou ceux qui ont un remplacement de moins de 20 matchs
df_passing = df_passing[(df_passing['Start Application'] >= 10) | (df_passing['Remplacement Application'] >= 20)]

In [50]:
df_defensive.count()

Name                        21428
Team                        21428
Age                         21428
Position                    21428
Minutes                     21428
Tackles per game            21428
Interceptions per game      21428
Fouls per game              21428
Offsides per game           21428
Clearances per game         21428
Dribbled past per game      21428
Outfield blocks per game    21428
Own goals                   21428
Rating                      21428
League                      21428
Saison                      21428
Start Application           21428
Remplacement Application    21428
dtype: int64

In [51]:
df_summary

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,Pass success percentage,Aerials won per game,Man of the match,Rating,League,Saison,Start Application,Remplacement Application
0,Neymar,Paris Saint-Germain,27,"Midfielder, Forward",1444,15,7,2,0,3.2,81.1,0.5,7,8.26,Ligue1,2018,16,1
1,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2344,33,7,5,1,4.3,79.4,0.1,9,8.00,Ligue1,2018,24,5
2,Téji Savanier,Nimes,27,"Defender, Midfielder",2866,6,14,7,1,2.1,71.4,1.6,8,7.89,Ligue1,2018,32,0
4,Nicolas Pepe,Lille,24,"Midfielder, Forward",3332,22,11,1,0,3.1,79.1,1.2,13,7.62,Ligue1,2018,37,1
5,Ángel Di María,Paris Saint-Germain,31,"Midfielder, Forward",2339,12,11,2,0,3.2,78.8,0.0,2,7.52,Ligue1,2018,28,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32935,Aaron Lennon,Burnley,35,Midfielder,1548,2,0,2,0,0.4,73.5,0.3,0,6.28,LaLiga,2019,17,11
32937,Ben Foster,Watford,39,Goalkeeper,2340,0,1,0,0,0.0,44.0,0.2,1,6.27,LaLiga,2019,26,0
32938,Mads Roerslev,Brentford,23,"Defender, Midfielder",1235,1,1,1,0,0.2,67.0,0.6,0,6.27,LaLiga,2019,12,9
32939,Steven Bergwijn,Tottenham,25,"Midfielder, Forward",551,3,1,1,0,0.8,84.2,0.2,0,6.25,LaLiga,2019,4,21
32941,Kieran Dowell,Norwich,25,"Midfielder, Forward",913,1,1,0,0,0.4,73.0,0.4,0,6.22,LaLiga,2019,11,8

### Modification de l'âge

**Les nouveaux datasets sont dans datasets**

In [52]:
# Extraire l'age et la date de naissance depuis FBREF
import pandas as pd
df = pd.read_csv("FBREF_dataset_full.csv")
# Créer un nouveau DataFrame avec les colonnes souhaitées
df_nouveau = pd.DataFrame({
    "Player": df["Player"],
    "Born": df["Born"]
})
# Enregistrer le dataframe modifié dans un nouveau fichier CSV
df_nouveau.to_csv('nom_annee.csv', index=False)

In [53]:
import pandas as pd

# Lecture des fichiers CSV
df_offensive = pd.read_csv('Offensive_Whoscored_Data.csv')
df_passing = pd.read_csv('Passing_Whoscored_Data.csv')
df_summary = pd.read_csv('Summary_Whoscored_Data.csv')
df_defensive = pd.read_csv('Defensive_Whoscored_Data.csv')

# Création d'une liste de datasets
datasets = [df_offensive, df_passing, df_summary, df_defensive]

# Lecture du fichier contenant les informations de naissance
df_nom_annee = pd.read_csv('nom_annee.csv')
df_nom_annee = df_nom_annee.rename(columns={'Player': 'Name'})

# Fonction pour mettre à jour la colonne "Born" et "Age"
def update_dataset(df):
    df = pd.merge(df, df_nom_annee[['Name', 'Born']], on='Name', how='left')
    df_with_na = df[df['Born'].isnull()]
    df_with_na["Born"] = df_with_na.apply(lambda x: 2018 - x["Age"] if x["Saison"] < 2019 else 2022 - x["Age"], axis=1)
    df["Born"] = df["Born"].fillna(df_with_na["Born"])
    df["Age"] = df.apply(lambda x: x["Saison"] - x["Born"], axis=1).astype(int)
    return df

# Boucle pour appliquer la fonction à chaque dataset de la liste "datasets"
for i in range(len(datasets)):
    datasets[i] = update_dataset(datasets[i])

<ipython-input-53-b57a8cac5dfa>:4: DtypeWarning: Columns (6,7,8,9,10,11,12,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df_offensive = pd.read_csv('Offensive_Whoscored_Data.csv')
<ipython-input-53-b57a8cac5dfa>:5: DtypeWarning: Columns (6,7,8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_passing = pd.read_csv('Passing_Whoscored_Data.csv')
<ipython-input-53-b57a8cac5dfa>:6: DtypeWarning: Columns (6,7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_summary = pd.read_csv('Summary_Whoscored_Data.csv')
<ipython-input-53-b57a8cac5dfa>:7: DtypeWarning: Columns (6,7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_defensive = pd.read_csv('Defensive_Whoscored_Data.csv')
<ipython-input-53-b57a8cac5dfa>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_with_na["Born"] = df_with_na.apply(lambda x: 2018 - x["Age"] if x["Saison"] < 2019 else 2022 - x["Age"], axis=1)
<ipython-input-53-b57a8cac5dfa>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_with_na["Born"] = df_with_na.apply(lambda x: 2018 - x["Age"] if x["Saison"] < 2019 else 2022 - x["Age"], axis=1)
<ipython-input-53-b57a8cac5dfa>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_with_na["Born"] = df_with_na.apply(lambda x: 2018 - x["Age"] if x["Saison"] < 2019 else 2022 - x["Age"], axis=1)
<ipython-input-53-b57a8cac5dfa>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_with_na["Born"] = df_with_na.apply(lambda x: 2018 - x["Age"] if x["Saison"] < 2019 else 2022 - x["Age"], axis=1)

In [54]:
datasets[3]

,Name,Team,Age,Position,Apps,Minutes,Tackles per game,Interceptions per game,Fouls per game,Offsides per game,Clearances per game,Dribbled past per game,Outfield blocks per game,Own goals,Rating,League,Saison,Born
0,Arjen Robben,Bayern Munich,25,"M(CLR),FW",18(6),1779,0.6,0.5,0.9,-,-,0.7,-,-,8.18,Bundesliga,2009,1984.0
1,Arjen Robben,Bayern Munich,25,"M(CLR),FW",18(6),1779,0.6,0.5,0.9,-,-,0.7,-,-,8.18,Bundesliga,2009,1984.0
2,Stefan Kießling,Bayer Leverkusen,25,FW,33,2924,1.2,0.7,2.5,-,0.3,0.5,0.1,-,7.79,Bundesliga,2009,1984.0
3,Zvjezdan Misimovic,Wolfsburg,28,"AM(C),FW",31,2768,1.9,0.6,1.5,-,0.2,1.2,0.1,-,7.74,Bundesliga,2009,1981.0
4,Edin Dzeko,Wolfsburg,24,FW,33(1),3003,0.5,0.1,1.9,-,0.9,0.2,0.1,-,7.73,Bundesliga,2009,1985.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71887,Karlan Grant,West Brom,23,"AM(CL),FW",14(7),1133,0.2,0.2,0.4,0.0,0.7,0.1,0.0,0,6.15,LaLiga,2020,1997.0
71888,Karlan Grant,West Brom,23,"AM(CL),FW",14(7),1133,0.2,0.2,0.4,0.0,0.7,0.1,0.0,0,6.15,LaLiga,2020,1997.0
71889,Hal Robson-Kanu,West Brom,31,"AM(LR),FW",2(17),549,0.1,0.1,0.8,0.0,0.4,0.1,0.0,0,6.13,LaLiga,2020,1989.0
71890,Hal Robson-Kanu,West Brom,31,"AM(LR),FW",2(17),549,0.1,0.1,0.8,0.0,0.4,0.1,0.0,0,6.13,LaLiga,2020,1989.0
71891,Romaine Sawyers,West Brom,29,M(CL),17(2),1490,1.6,0.9,0.9,0.1,0.5,1.5,0.2,1,6.12,LaLiga,2020,1991.0

In [55]:
for i in range(len(datasets)):
    datasets[i] =  datasets[i].drop_duplicates()
datasets[2].loc[datasets[2].Name == 'Cristiano Ronaldo']

,Name,Team,Age,Position,Apps,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,Pass success percentage,Aerials won per game,Man of the match,Rating,League,Saison,Born
9352,Cristiano Ronaldo,Man Utd,36,"M(L),FW",27(3),2459,18,3,8,0,3.7,81.9,1.4,5,7.11,LaLiga,2021,1985.0
16320,Cristiano Ronaldo,Juventus,33,"M(L),FW",30(1),2689,21,8,3,-,5.7,85.1,1.1,10,7.68,SerieA,2018,1985.0
24955,Cristiano Ronaldo,Man Utd,36,"M(L),FW",27(3),2459,18,3,8,0,3.7,81.9,1.4,5,7.11,PremierLeague,2021,1985.0
29707,Cristiano Ronaldo,Man Utd,34,"M(L),FW",27(3),2459,18,3,8,0,3.7,81.9,1.4,5,7.11,PremierLeague,2019,1985.0
32659,Cristiano Ronaldo,Real Madrid,30,"M(L),FW",36,3185,35,11,3,-,6.3,79.4,1.6,8,7.99,LaLiga,2015,1985.0
34766,Cristiano Ronaldo,Real Madrid,26,"M(L),FW",37(1),3354,46,12,4,-,6.9,80.6,0.8,11,8.28,LaLiga,2011,1985.0
37585,Cristiano Ronaldo,Real Madrid,29,"M(L),FW",35,3099,48,16,5,1,6.4,80.7,1.7,17,8.48,LaLiga,2014,1985.0
45604,Cristiano Ronaldo,Real Madrid,31,"M(L),FW",29,2544,25,6,4,-,5.6,80,1.2,4,7.61,LaLiga,2016,1985.0
47743,Cristiano Ronaldo,Real Madrid,25,"M(L),FW",32(2),2913,40,11,2,-,7.4,75.7,1.4,12,8.35,LaLiga,2010,1985.0
50502,Cristiano Ronaldo,Real Madrid,27,"M(L),FW",30(4),2721,34,10,9,-,6.9,76.7,1.6,11,8.15,LaLiga,2012,1985.0
51557,Cristiano Ronaldo,Juventus,34,"M(L),FW",33,2919,31,5,3,0,6.3,85.1,1.2,10,7.82,SerieA,2019,1985.0
52723,Cristiano Ronaldo,Real Madrid,32,"M(L),FW",27,2293,26,5,1,-,6.6,81.6,1.3,7,7.94,LaLiga,2017,1985.0
62230,Cristiano Ronaldo,Real Madrid,28,"M(L),FW",30,2545,31,9,4,1,7.2,80.2,1.8,10,8.27,LaLiga,2013,1985.0
69957,Cristiano Ronaldo,Real Madrid,24,"M(L),FW",28(1),2490,26,7,3,2,7.3,79.7,0.9,13,8.54,LaLiga,2009,1985.0
70918,Cristiano Ronaldo,Man Utd,34,"M(L),FW",27(3),2459,18,3,8,0,3.7,81.9,1.4,5,7.11,LaLiga,2019,1985.0

In [56]:
datasets[2].loc[datasets[2].Name== 'Kylian Mbappé']

,Name,Team,Age,Position,Apps,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,Pass success percentage,Aerials won per game,Man of the match,Rating,League,Saison,Born
1,Kylian Mbappé,Paris Saint-Germain,20,"AM(LR),FW",24(5),2344,33,7,5,1,4.3,79.4,0.1,9,8.00,Ligue1,2018,1998.0
3324,Kylian Mbappé,PSG,22,"AM(LR),FW",27(4),2389,27,7,5,0,3.4,80.7,0.2,6,7.68,Ligue1,2020,1998.0
30682,Kylian Mbappé,PSG,21,"AM(LR),FW",17(3),1516,18,5,0,0,4.4,80.4,0.2,6,8.14,Ligue1,2019,1998.0
34072,Kylian Mbappé,Monaco,18,"AM(LR),FW",17(12),1501,15,8,2,-,1.8,73.3,0.3,5,7.22,Ligue1,2016,1998.0
38759,Kylian Mbappé,PSG,24,"AM(LR),FW",20(2),1742,18,3,4,0,4.2,82.7,0.3,3,7.79,Ligue1,2022,1998.0
47042,Kylian Mbappé,Paris Saint-Germain,19,"AM(LR),FW",24(3),2097,13,8,2,-,2.9,83.1,0.3,7,7.54,Ligue1,2017,1998.0
47049,Kylian Mbappé,Monaco,19,"AM(LR),FW",1,75,-,-,-,-,3,70.4,-,-,7.51,Ligue1,2017,1998.0
64949,Kylian Mbappé,Monaco,17,"AM(LR),FW",2(9),288,1,1,1,-,0.5,70.5,0.1,-,6.34,Ligue1,2015,1998.0
65067,Kylian Mbappé,PSG,23,"AM(LR),FW",34(1),3032,28,17,10,0,4.2,82.2,0.1,12,8.04,Ligue1,2021,1998.0

In [57]:
#df_offensive = datasets[0]
#df_passing = datasets[1]
#df_summary = datasets[2]
#df_defensive = datasets[3]

### Différencier les positions selon les bases de données
##### Mettre les "Midfielder" et "Foward" seulement dans Passing et aussi dans Offensive
##### Mettre les "Midfielder" et "Defensive", "Goalkeeper" seulement dans Defensive
##### Mettre summary dans chacun des database

In [ ]:
def merge_dataframes(dataframes):
    """
    Fusionne plusieurs dataframes en utilisant les colonnes qui se retrouvent dans chaque dataframe
    en tant que clés de fusion.

    :param dataframes: une liste de dataframes à fusionner.
    :return: le dataframe fusionné.
    """
    df_merged = dataframes[0]

    for i in range(1, len(dataframes)):
        df_merged = pd.merge(df_merged, dataframes[i], on=list(set(df_merged.columns) & set(dataframes[i].columns)), how="outer")

    return df_merged

In [ ]:
def create_position_databases(df):
    # Liste des positions à garder pour chaque base de données
    midfield_positions = ['Midfielder', 'Defender, Midfielder, Forward', 'Midfielder, Forward', 'Defender, Midfielder']
    forward_positions = ['Forward', 'Defender, Forward', 'Midfielder, Forward']
    defensive_positions = ['Defender', 'Defender, Midfielder, Forward', 'Defender, Forward', 'Defender, Midfielder']
    goalkeeper_positions = ['Goalkeeper']
    
   
    # Filtrer les positions et créer les bases de données correspondantes
    df_midfield = df[df['Position'].isin(midfield_positions)]
    df_midfield = merge_dataframes([df_midfield,df_passing])
    df_midfield = merge_dataframes([df_midfield,df_offensive])
    df_midfield = df_midfield.drop('Total goals', axis=1)
    df_midfield = df_midfield[df_midfield['Position'].isin(midfield_positions)]
    
    df_forward = df[df['Position'].isin(forward_positions)]
    df_forward = merge_dataframes([df_forward,df_passing])
    df_forward = merge_dataframes([df_midfield,df_offensive])
    df_forward = df_forward.drop('Total goals', axis=1)
    df_forward = df_forward[df_forward['Position'].isin(forward_positions)]
    
    df_defense = df[df['Position'].isin(defensive_positions)]
    df_defense = merge_dataframes([df_defense,df_passing])
    df_defense = merge_dataframes([df_defense,df_defensive])
    df_defense = df_defense[df_defense['Position'].isin(defensive_positions)]
    
    df_goalkeeper = df[df['Position'].isin(goalkeeper_positions)]
    df_goalkeeper = merge_dataframes([df_goalkeeper,df_defensive])
    df_goalkeeper = df_goalkeeper[df_goalkeeper['Position'].isin(goalkeeper_positions)]
    
    # Enregistrer les bases de données dans des fichiers CSV
    df_midfield.to_csv('midfield_players.csv', index=False)
    df_forward.to_csv('forward_players.csv', index=False)
    df_defensive.to_csv('defensive_players.csv', index=False)
    df_goalkeeper.to_csv('goalkeeper_players.csv', index=False)

In [ ]:
create_position_databases(df_summary)

In [ ]:
df_midfield = pd.read_csv('midfield_players.csv')
df_midfield

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,...,Passes per game,Crosses per game,Long balls per game,Through balls per game,Dribbles per game,Fouled per game,Offsides per game,Dispossessed per game,Bad control per game,Dribble
0,Neymar,Paris Saint-Germain,27,"Midfielder, Forward",1444,15.0,7,2.0,0.0,3.2,...,57.8,1.0,2.5,0.9,4.4,3.4,0.4,4.2,4.1,0.0
1,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2344,33.0,7,5.0,1.0,4.3,...,26.9,0.2,0.6,0.1,2.2,1.5,1.0,1.5,2.1,0.0
2,Téji Savanier,Nimes,27,"Defender, Midfielder",2866,6.0,14,7.0,1.0,2.1,...,50.4,2.3,6.6,0.1,2.5,3.0,0.0,1.3,2.0,0.0
3,Nicolas Pepe,Lille,24,"Midfielder, Forward",3332,22.0,11,1.0,0.0,3.1,...,31.6,0.4,0.7,0.3,2.7,2.8,0.3,2.9,2.9,0.0
4,Ángel Di María,Paris Saint-Germain,31,"Midfielder, Forward",2339,12.0,11,2.0,0.0,3.2,...,42.1,1.0,1.7,0.2,1.4,0.6,0.2,1.5,1.6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13481,Mads Roerslev,Brentford,23,"Defender, Midfielder",1235,1.0,1,1.0,0.0,0.2,...,14.1,0.4,0.5,0.0,0.0,0.4,0.1,0.2,0.4,0.2
13482,Steven Bergwijn,Tottenham,25,"Midfielder, Forward",551,3.0,1,1.0,0.0,0.8,...,6.6,0.0,0.0,0.0,0.0,0.4,0.0,0.6,1.1,0.4
13483,Kieran Dowell,Norwich,25,"Midfielder, Forward",913,1.0,1,0.0,0.0,0.4,...,15.4,0.5,0.5,0.0,0.0,0.2,0.0,0.8,0.7,0.4
13484,Grégory Bourillon,Lorient,35,"Defender, Midfielder",1789,NaN,2,NaN,NaN,NaN,...,37.1,0.0,4.8,0.1,NaN,NaN,NaN,NaN,NaN,NaN
13485,Grégory Bourillon,Lorient,35,"Defender, Midfielder",1789,NaN,2,NaN,NaN,0.5,...,NaN,NaN,NaN,NaN,0.1,0.4,0.0,0.1,0.2,0.0

In [ ]:
df_midfield.loc[df_midfield.Name == 'Kylian Mbappé']

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,...,Passes per game,Crosses per game,Long balls per game,Through balls per game,Dribbles per game,Fouled per game,Offsides per game,Dispossessed per game,Bad control per game,Dribble
1,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2344,33.0,7,5.0,1.0,4.3,...,26.9,0.2,0.6,0.1,2.2,1.5,1.0,1.5,2.1,0.0
598,Kylian Mbappé,PSG,24,"Midfielder, Forward",2389,27.0,7,5.0,0.0,3.4,...,30.7,0.2,0.2,0.0,0.0,1.2,0.5,1.5,2.6,2.9
5497,Kylian Mbappé,PSG,24,"Midfielder, Forward",1516,18.0,5,0.0,0.0,4.4,...,30.1,0.4,0.5,0.1,0.0,1.1,0.9,1.3,2.4,2.8
6274,Kylian Mbappé,Monaco,20,"Midfielder, Forward",1501,15.0,8,2.0,0.0,1.8,...,11.6,0.2,0.3,0.0,1.1,0.8,0.8,1.1,1.9,0.0
7180,Kylian Mbappé,PSG,24,"Midfielder, Forward",1742,18.0,3,4.0,0.0,4.2,...,34.2,0.5,0.3,0.1,0.0,1.1,0.9,1.1,1.8,2.0
8774,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2097,13.0,8,2.0,0.0,2.9,...,24.7,0.4,0.3,0.3,2.9,1.4,0.9,2.2,2.4,0.0
12101,Kylian Mbappé,PSG,24,"Midfielder, Forward",3032,28.0,17,10.0,0.0,4.2,...,38.3,0.6,1.2,0.1,0.0,1.5,1.1,1.6,3.2,3.2

In [ ]:
df_forward = pd.read_csv('forward_players.csv')
df_forward

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,...,Passes per game,Crosses per game,Long balls per game,Through balls per game,Dribbles per game,Fouled per game,Offsides per game,Dispossessed per game,Bad control per game,Dribble
0,Neymar,Paris Saint-Germain,27,"Midfielder, Forward",1444,15.0,7,2.0,0.0,3.2,...,57.8,1.0,2.5,0.9,4.4,3.4,0.4,4.2,4.1,0.0
1,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2344,33.0,7,5.0,1.0,4.3,...,26.9,0.2,0.6,0.1,2.2,1.5,1.0,1.5,2.1,0.0
2,Nicolas Pepe,Lille,24,"Midfielder, Forward",3332,22.0,11,1.0,0.0,3.1,...,31.6,0.4,0.7,0.3,2.7,2.8,0.3,2.9,2.9,0.0
3,Ángel Di María,Paris Saint-Germain,31,"Midfielder, Forward",2339,12.0,11,2.0,0.0,3.2,...,42.1,1.0,1.7,0.2,1.4,0.6,0.2,1.5,1.6,0.0
4,Edinson Cavani,Paris Saint-Germain,32,"Midfielder, Forward",1676,18.0,5,1.0,0.0,2.5,...,16.7,0.0,0.3,0.0,0.6,0.8,0.5,0.6,1.8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5799,Chris Wood,Burnley,31,Forward,2750,NaN,3,NaN,NaN,2.1,...,NaN,NaN,NaN,NaN,0.0,0.7,0.7,1.3,2.4,0.2
5800,Tammy Abraham,Chelsea,25,Forward,1036,NaN,1,NaN,NaN,1.5,...,NaN,NaN,NaN,NaN,0.0,0.5,0.2,0.3,1.5,0.3
5801,Aleksandar Mitrovic,Fulham,28,Forward,1390,NaN,3,NaN,NaN,2.2,...,NaN,NaN,NaN,NaN,0.0,0.9,0.1,0.6,2.2,0.3
5802,Fábio Silva,Wolves,20,Forward,1357,NaN,3,NaN,NaN,1.5,...,NaN,NaN,NaN,NaN,0.0,0.7,0.2,0.7,1.4,0.2
5803,Rhian Brewster,Sheff Utd,22,Forward,1125,NaN,0,NaN,NaN,0.9,...,NaN,NaN,NaN,NaN,0.0,0.5,0.1,0.7,0.7,0.3

In [ ]:
df_defense = pd.read_csv('defensive_players.csv')
df_defense

,Name,Team,Age,Position,Minutes,Tackles per game,Interceptions per game,Fouls per game,Offsides per game,Clearances per game,Dribbled past per game,Outfield blocks per game,Own goals,Rating,League,Saison,Start Application,Remplacement Application
0,Arjen Robben,Bayern Munich,35,"Midfielder, Forward",1779,0.6,0.5,0.9,0.0,0.0,0.7,0.0,0,8.18,Bundesliga,2009,18,6
1,Stefan Kießling,Bayer Leverkusen,35,Forward,2924,1.2,0.7,2.5,0.0,0.3,0.5,0.1,0,7.79,Bundesliga,2009,33,0
2,Zvjezdan Misimovic,Wolfsburg,37,"Midfielder, Forward",2768,1.9,0.6,1.5,0.0,0.2,1.2,0.1,0,7.74,Bundesliga,2009,31,0
3,Edin Dzeko,Wolfsburg,33,Forward,3003,0.5,0.1,1.9,0.0,0.9,0.2,0.1,0,7.73,Bundesliga,2009,33,1
4,Claudio Pizarro,Werder Bremen,40,"Midfielder, Forward",2130,1.0,0.7,2.0,0.0,0.7,0.4,0.2,0,7.63,Bundesliga,2009,23,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21423,John Lundstram,Sheff Utd,29,"Defender, Midfielder",2032,0.9,0.5,0.9,0.1,0.8,1.2,0.3,0,6.23,LaLiga,2020,23,5
21424,Ibrahima Diallo,Southampton,24,"Defender, Midfielder",1012,1.3,0.5,1.0,0.0,0.5,0.3,0.0,0,6.22,LaLiga,2020,10,12
21425,Rhian Brewster,Sheff Utd,22,Forward,1125,0.3,0.2,0.7,0.0,0.1,0.4,0.1,0,6.17,LaLiga,2020,12,15
21426,Karlan Grant,West Brom,25,"Midfielder, Forward",1133,0.2,0.2,0.4,0.0,0.7,0.1,0.0,0,6.15,LaLiga,2020,14,7
21427,Romaine Sawyers,West Brom,31,Midfielder,1490,1.6,0.9,0.9,0.1,0.5,1.5,0.2,1,6.12,LaLiga,2020,17,2

In [ ]:
df_goalkeeper = pd.read_csv('goalkeeper_players.csv')
df_goalkeeper

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,...,Start Application,Remplacement Application,Tackles per game,Interceptions per game,Fouls per game,Offsides per game,Clearances per game,Dribbled past per game,Outfield blocks per game,Own goals
0,Bobby Allain,Dijon,27,Goalkeeper,1170,0.0,0.0,1.0,0.0,0.0,...,13,0,0.0,0.0,0.1,0.0,1.6,0.1,0.0,0
1,Walter Benítez,Nice,26,Goalkeeper,3150,0.0,0.0,1.0,0.0,0.0,...,35,0,0.0,0.1,0.0,0.0,0.6,0.0,0.0,0
2,Gianluigi Buffon,Paris Saint-Germain,41,Goalkeeper,1530,0.0,0.0,0.0,0.0,0.0,...,17,0,0.0,0.0,0.0,0.0,0.5,0.1,0.0,0
3,Benjamin Lecomte,Montpellier,28,Goalkeeper,3330,0.0,0.0,1.0,0.0,0.0,...,37,0,0.0,0.1,0.0,0.0,1.2,0.1,0.0,0
4,Stéphane Ruffier,Saint-Etienne,32,Goalkeeper,3330,0.0,0.0,1.0,0.0,0.0,...,37,0,0.1,0.0,0.1,0.0,0.9,0.1,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1577,Emiliano Martínez,Aston Villa,30,Goalkeeper,3240,0.0,0.0,4.0,0.0,0.0,...,36,0,0.0,0.0,0.0,0.0,0.3,0.1,0.0,0
1578,Illan Meslier,Leeds,23,Goalkeeper,3385,0.0,0.0,2.0,0.0,0.0,...,38,0,0.0,0.0,0.0,0.0,1.2,0.0,0.0,0
1579,Jordan Pickford,Everton,29,Goalkeeper,3150,0.0,0.0,2.0,0.0,0.0,...,35,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0
1580,Tim Krul,Norwich,34,Goalkeeper,2610,0.0,0.0,1.0,0.0,0.0,...,29,0,0.0,0.0,0.0,0.0,0.9,0.1,0.0,1
1581,Ben Foster,Watford,39,Goalkeeper,2340,0.0,1.0,0.0,0.0,0.0,...,26,0,0.0,0.0,0.0,0.0,0.6,0.1,0.0,0

In [ ]:
df_list_pos = [df_goalkeeper, df_defensive, df_forward, df_midfield]
for df in df_list_pos:
    df.fillna(0, inplace=True)
    
convert_to_int(df_list_pos)

for df in df_list_pos:
    print(df.dtypes)

C:\Users\lucas\AppData\Local\Temp\ipykernel_52188\3626313309.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
C:\Users\lucas\AppData\Local\Temp\ipykernel_52188\2580584036.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], downcast='integer')

Name                         object
Team                         object
Age                            int8
Position                     object
Minutes                       int16
Total Goals                    int8
Total Assists                  int8
Yellow cards                   int8
Red cards                      int8
Shots per game              float64
Pass success percentage     float64
Aerials won per game        float64
Man of the match               int8
Rating                      float64
League                       object
Saison                        int16
Start Application              int8
Remplacement Application       int8
Tackles per game            float64
Interceptions per game      float64
Fouls per game              float64
Offsides per game           float64
Clearances per game         float64
Dribbled past per game      float64
Outfield blocks per game    float64
Own goals                      int8
dtype: object
Name                         object
Team                         object
Age                            int8
Position                     object
Minutes                       int16
Tackles per game            float64
Interceptions per game      float64
Fouls per game              float64
Offsides per game           float64
Clearances per game         float64
Dribbled past per game      float64
Outfield blocks per game    float64
Own goals                      int8
Rating                      float64
League                       object
Saison                        int16
Start Application              int8
Remplacement Application       int8
dtype: object
Name                         object
Team                         object
Age                            int8
Position                     object
Minutes                       int16
Total Goals                    int8
Total Assists                  int8
Yellow cards                   int8
Red cards                      int8
Shots per game              float64
Pass success percentage     float64
Aerials won per game        float64
Man of the match               int8
Rating                      float64
League                       object
Saison                        int16
Start Application              int8
Remplacement Application       int8
Key passes per game         float64
Passes per game             float64
Crosses per game            float64
Long balls per game         float64
Through balls per game      float64
Dribbles per game           float64
Fouled per game             float64
Offsides per game           float64
Dispossessed per game       float64
Bad control per game        float64
Dribble                     float64
dtype: object
Name                         object
Team                         object
Age                            int8
Position                     object
Minutes                       int16
Total Goals                    int8
Total Assists                  int8
Yellow cards                   int8
Red cards                      int8
Shots per game              float64
Pass success percentage     float64
Aerials won per game        float64
Man of the match               int8
Rating                      float64
League                       object
Saison                        int16
Start Application              int8
Remplacement Application       int8
Key passes per game         float64
Passes per game             float64
Crosses per game            float64
Long balls per game         float64
Through balls per game      float64
Dribbles per game           float64
Fouled per game             float64
Offsides per game           float64
Dispossessed per game       float64
Bad control per game        float64
Dribble                     float64
dtype: object

In [ ]:
df_goalkeeper.loc[df_goalkeeper.Name == 'Kylian Mbappé']

Empty DataFrame
Columns: [Name, Team, Age, Position, Minutes, Total Goals, Total Assists, Yellow cards, Red cards, Shots per game, Pass success percentage, Aerials won per game, Man of the match, Rating, League, Saison, Start Application, Remplacement Application, Tackles per game, Interceptions per game, Fouls per game, Offsides per game, Clearances per game, Dribbled past per game, Outfield blocks per game, Own goals]
Index: []

[0 rows x 26 columns]

In [ ]:
df_midfield.loc[df_midfield.Name == 'Kylian Mbappé']

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,...,Passes per game,Crosses per game,Long balls per game,Through balls per game,Dribbles per game,Fouled per game,Offsides per game,Dispossessed per game,Bad control per game,Dribble
1,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2344,33,7,5,1,4.3,...,26.9,0.2,0.6,0.1,2.2,1.5,1.0,1.5,2.1,0.0
598,Kylian Mbappé,PSG,24,"Midfielder, Forward",2389,27,7,5,0,3.4,...,30.7,0.2,0.2,0.0,0.0,1.2,0.5,1.5,2.6,2.9
5497,Kylian Mbappé,PSG,24,"Midfielder, Forward",1516,18,5,0,0,4.4,...,30.1,0.4,0.5,0.1,0.0,1.1,0.9,1.3,2.4,2.8
6274,Kylian Mbappé,Monaco,20,"Midfielder, Forward",1501,15,8,2,0,1.8,...,11.6,0.2,0.3,0.0,1.1,0.8,0.8,1.1,1.9,0.0
7180,Kylian Mbappé,PSG,24,"Midfielder, Forward",1742,18,3,4,0,4.2,...,34.2,0.5,0.3,0.1,0.0,1.1,0.9,1.1,1.8,2.0
8774,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2097,13,8,2,0,2.9,...,24.7,0.4,0.3,0.3,2.9,1.4,0.9,2.2,2.4,0.0
12101,Kylian Mbappé,PSG,24,"Midfielder, Forward",3032,28,17,10,0,4.2,...,38.3,0.6,1.2,0.1,0.0,1.5,1.1,1.6,3.2,3.2

In [ ]:
df_midfield.loc[df_midfield.Name == 'Kylian Mbappé', ['Saison', 'Name']]

       Saison           Name
1        2018  Kylian Mbappé
598      2020  Kylian Mbappé
5497     2019  Kylian Mbappé
6274     2016  Kylian Mbappé
7180     2022  Kylian Mbappé
8774     2017  Kylian Mbappé
12101    2021  Kylian Mbappé

In [ ]:
df_midfield.loc[df_midfield.Name == 'Kylian Mbappé']

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,...,Passes per game,Crosses per game,Long balls per game,Through balls per game,Dribbles per game,Fouled per game,Offsides per game,Dispossessed per game,Bad control per game,Dribble
1,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2344,33,7,5,1,4.3,...,26.9,0.2,0.6,0.1,2.2,1.5,1.0,1.5,2.1,0.0
598,Kylian Mbappé,PSG,24,"Midfielder, Forward",2389,27,7,5,0,3.4,...,30.7,0.2,0.2,0.0,0.0,1.2,0.5,1.5,2.6,2.9
5497,Kylian Mbappé,PSG,24,"Midfielder, Forward",1516,18,5,0,0,4.4,...,30.1,0.4,0.5,0.1,0.0,1.1,0.9,1.3,2.4,2.8
6274,Kylian Mbappé,Monaco,20,"Midfielder, Forward",1501,15,8,2,0,1.8,...,11.6,0.2,0.3,0.0,1.1,0.8,0.8,1.1,1.9,0.0
7180,Kylian Mbappé,PSG,24,"Midfielder, Forward",1742,18,3,4,0,4.2,...,34.2,0.5,0.3,0.1,0.0,1.1,0.9,1.1,1.8,2.0
8774,Kylian Mbappé,Paris Saint-Germain,20,"Midfielder, Forward",2097,13,8,2,0,2.9,...,24.7,0.4,0.3,0.3,2.9,1.4,0.9,2.2,2.4,0.0
12101,Kylian Mbappé,PSG,24,"Midfielder, Forward",3032,28,17,10,0,4.2,...,38.3,0.6,1.2,0.1,0.0,1.5,1.1,1.6,3.2,3.2

In [ ]:
    # Enregistrer les bases de données dans des fichiers CSV
    df_midfield.to_csv('midfield_players.csv', index=False)
    df_forward.to_csv('forward_players.csv', index=False)
    df_defensive.to_csv('defensive_players.csv', index=False)
    df_goalkeeper.to_csv('goalkeeper_players.csv', index=False)

# Merge All Database :

In [ ]:
# Fusionner les dataframes
df_merged = merge_dataframes(df_list_pos)

In [ ]:
df_merged

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,...,Key passes per game,Passes per game,Crosses per game,Long balls per game,Through balls per game,Dribbles per game,Fouled per game,Dispossessed per game,Bad control per game,Dribble
0,Bobby Allain,Dijon,27,Goalkeeper,1170,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Walter Benítez,Nice,26,Goalkeeper,3150,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Gianluigi Buffon,Paris Saint-Germain,41,Goalkeeper,1530,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Benjamin Lecomte,Montpellier,28,Goalkeeper,3330,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Stéphane Ruffier,Saint-Etienne,32,Goalkeeper,3330,0.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36716,Tom Cleverley,Watford,33,Midfielder,1626,0.0,2.0,2.0,0.0,0.4,...,0.7,21.3,0.6,0.9,0.0,0.0,0.7,0.6,0.6,0.1
36717,Aaron Lennon,Burnley,35,Midfielder,1548,2.0,0.0,2.0,0.0,0.4,...,0.3,12.0,0.1,0.3,0.0,0.0,0.7,0.5,0.9,0.5
36718,Mads Roerslev,Brentford,23,"Defender, Midfielder",1235,1.0,1.0,1.0,0.0,0.2,...,0.3,14.1,0.4,0.5,0.0,0.0,0.4,0.2,0.4,0.2
36719,Grégory Bourillon,Lorient,35,"Defender, Midfielder",1789,0.0,2.0,0.0,0.0,0.0,...,0.5,37.1,0.0,4.8,0.1,0.0,0.0,0.0,0.0,0.0
36720,Grégory Bourillon,Lorient,35,"Defender, Midfielder",1789,0.0,2.0,0.0,0.0,0.5,...,0.5,0.0,0.0,0.0,0.0,0.1,0.4,0.1,0.2,0.0

In [ ]:
df_merged.fillna(0, inplace=True)
df_merged

,Name,Team,Age,Position,Minutes,Total Goals,Total Assists,Yellow cards,Red cards,Shots per game,...,Key passes per game,Passes per game,Crosses per game,Long balls per game,Through balls per game,Dribbles per game,Fouled per game,Dispossessed per game,Bad control per game,Dribble
0,Bobby Allain,Dijon,27,Goalkeeper,1170,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Walter Benítez,Nice,26,Goalkeeper,3150,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Gianluigi Buffon,Paris Saint-Germain,41,Goalkeeper,1530,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Benjamin Lecomte,Montpellier,28,Goalkeeper,3330,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Stéphane Ruffier,Saint-Etienne,32,Goalkeeper,3330,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36716,Tom Cleverley,Watford,33,Midfielder,1626,0.0,2.0,2.0,0.0,0.4,...,0.7,21.3,0.6,0.9,0.0,0.0,0.7,0.6,0.6,0.1
36717,Aaron Lennon,Burnley,35,Midfielder,1548,2.0,0.0,2.0,0.0,0.4,...,0.3,12.0,0.1,0.3,0.0,0.0,0.7,0.5,0.9,0.5
36718,Mads Roerslev,Brentford,23,"Defender, Midfielder",1235,1.0,1.0,1.0,0.0,0.2,...,0.3,14.1,0.4,0.5,0.0,0.0,0.4,0.2,0.4,0.2
36719,Grégory Bourillon,Lorient,35,"Defender, Midfielder",1789,0.0,2.0,0.0,0.0,0.0,...,0.5,37.1,0.0,4.8,0.1,0.0,0.0,0.0,0.0,0.0
36720,Grégory Bourillon,Lorient,35,"Defender, Midfielder",1789,0.0,2.0,0.0,0.0,0.5,...,0.5,0.0,0.0,0.0,0.0,0.1,0.4,0.1,0.2,0.0

In [ ]:
df_merged.dtypes
exclude_cols = ['Name', 'Team', 'Position', 'League']

In [ ]:
convert_to_int([df_merged])
df_merged.dtypes

Name                         object
Team                         object
Age                            int8
Position                     object
Minutes                       int16
Total Goals                    int8
Total Assists                  int8
Yellow cards                   int8
Red cards                      int8
Shots per game              float64
Pass success percentage     float64
Aerials won per game        float64
Man of the match               int8
Rating                      float64
League                       object
Saison                        int16
Start Application              int8
Remplacement Application       int8
Tackles per game            float64
Interceptions per game      float64
Fouls per game              float64
Offsides per game           float64
Clearances per game         float64
Dribbled past per game      float64
Outfield blocks per game    float64
Own goals                      int8
Key passes per game         float64
Passes per game             float64
Crosses per game            float64
Long balls per game         float64
Through balls per game      float64
Dribbles per game           float64
Fouled per game             float64
Dispossessed per game       float64
Bad control per game        float64
Dribble                     float64
dtype: object

In [ ]:
df_merged.loc[df_merged.Name == 'Cristiano Ronaldo', ['Saison', 'Name']]

       Saison               Name
1858     2021  Cristiano Ronaldo
3531     2010  Cristiano Ronaldo
7510     2019  Cristiano Ronaldo
8680     2012  Cristiano Ronaldo
10052    2018  Cristiano Ronaldo
10364    2019  Cristiano Ronaldo
11461    2011  Cristiano Ronaldo
12390    2009  Cristiano Ronaldo
13303    2017  Cristiano Ronaldo
13623    2015  Cristiano Ronaldo
14845    2019  Cristiano Ronaldo
15091    2016  Cristiano Ronaldo
16802    2021  Cristiano Ronaldo
17271    2014  Cristiano Ronaldo
19156    2013  Cristiano Ronaldo
22020    2021  Cristiano Ronaldo
22451    2018  Cristiano Ronaldo
22853    2021  Cristiano Ronaldo
23168    2019  Cristiano Ronaldo
23400    2015  Cristiano Ronaldo
23535    2011  Cristiano Ronaldo
23679    2014  Cristiano Ronaldo
24172    2016  Cristiano Ronaldo
24328    2010  Cristiano Ronaldo
24951    2012  Cristiano Ronaldo
25004    2019  Cristiano Ronaldo
25063    2017  Cristiano Ronaldo
25561    2013  Cristiano Ronaldo
26068    2009  Cristiano Ronaldo
26136    2019  Cristiano Ronaldo

In [ ]:
def remove_duplicate_rows(dfs):
    """
    Supprime les lignes en double dans chaque dataframe de la liste 'dfs' en fonction des colonnes 'Name' et 'Saison'
    """
    for df in dfs:
        df.drop_duplicates(subset=['Name', 'Saison'], inplace=True)
        df.drop_duplicates(subset=['Saison'], keep='first', inplace=True)
    return dfs

In [ ]:
remove_duplicate_rows(df_merged)

AttributeError: 'str' object has no attribute 'drop_duplicates'

In [ ]:
df_merged.loc[df_merged.Name == 'Kylian Mbappé', ['Saison', 'Name']]

       Saison           Name
5008     2017  Kylian Mbappé
5524     2019  Kylian Mbappé
5768     2018  Kylian Mbappé
9575     2022  Kylian Mbappé
11188    2021  Kylian Mbappé
12097    2020  Kylian Mbappé
13971    2016  Kylian Mbappé
21429    2018  Kylian Mbappé
21643    2020  Kylian Mbappé
23238    2019  Kylian Mbappé
23468    2016  Kylian Mbappé
23750    2022  Kylian Mbappé
24245    2017  Kylian Mbappé
25754    2021  Kylian Mbappé

In [ ]:
df_merged.to_csv('Merged_players.csv', index=False)